// nv_fonts — extended Montserrat LVGL fonts: ASCII + Latin-1 accents (à é ñ ü ç ß …) +
// the LVGL symbol glyphs. Drop-in replacements for the ASCII-only built-in montserrat,
// so localized (IT/ES/FR/DE) UI text renders correctly. Generated by tools/gen_fonts.ps1.
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t nv_font_14;
extern const lv_font_t nv_font_20;
extern const lv_font_t nv_font_28;

#ifdef __cplusplus
}
#endif
