// ANIMA offline intent SUGGESTER: when every rule missed, the closest known request, to be OFFERED
// ("Intendi «alza il volume»? (sì/no)") and run only on a yes. A multinomial logistic regression over hashed
// binary features (words, word pairs, char 3-5-grams; the fastText-supervised recipe), int8 weights in
// flash (anima_intent_model.c, generated by tools/train_anima_intent.py, which mirrors this file exactly).
#pragma once
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// Gate: below either, no suggestion. Kept equal to P_MIN / MARGIN in tools/train_anima_intent.py.
#define ANIMA_INTENT_P_MIN   0.45f
#define ANIMA_INTENT_MARGIN  0.15f

// The model (generated).
extern const int anima_intent_nb, anima_intent_nc;
extern const float anima_intent_scale;
extern const char *const anima_intent_label[];      // a canonical phrase, or "-" = not a request
extern const unsigned char anima_intent_en[];       // 1 = the canonical is English
extern const float anima_intent_bias[];
extern const signed char anima_intent_w[];          // [bucket][class]

// Top class of `text` and its probability (the raw model, no gate). Returns the class index.
int anima_intent_top(const char *text, float *p_top, float *p_second);
// The canonical phrase to OFFER for `text` in that language, or NULL: under the gate, "-", another
// language, or a direction that contradicts the words said ("più silenzio" is never "alza il volume").
const char *anima_intent_suggest(const char *text, bool en, float *p_out);
// The polarity guard alone: false when `text` and `canon` point opposite ways (up/down, open/close).
bool anima_intent_compatible(const char *text, const char *canon);

#ifdef __cplusplus
}
#endif
