// ANIMA L0 paraphrase table (anima_phrases.c, generated by tools/gen_anima_phrases.py from
// tools/anima_phrases.txt): the many ways people say a request -> the canonical phrase L0 understands.
#pragma once
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// A word the paraphrase key ignores ("per favore", "puoi", articles; "please", "the"...).
bool anima_phrase_is_filler(bool en, const char *w);
// key = "it:" / "en:" + the normalized tokens without fillers, space-joined. NULL = not a paraphrase.
const char *anima_phrase_lookup(const char *key);
int anima_phrase_count(void);

#ifdef __cplusplus
}
#endif
