// Generated by tools/gen_ss_icons.py — Second Screen wizard icons (A8: tint with image_recolor).
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t ss_ic_win;   // microsoft-windows 64px
extern const lv_image_dsc_t ss_ic_apple;   // apple 64px
extern const lv_image_dsc_t ss_ic_linux;   // linux 64px
extern const lv_image_dsc_t ss_ic_android;   // android 64px
extern const lv_image_dsc_t ss_ic_web;   // web 64px
extern const lv_image_dsc_t ss_ic_screen;   // monitor-share 96px
extern const lv_image_dsc_t ss_ic_usb;   // usb 40px
extern const lv_image_dsc_t ss_ic_wifi;   // wifi 40px
extern const lv_image_dsc_t ss_ic_vnc;   // remote-desktop 40px
extern const lv_image_dsc_t ss_ic_cast;   // cast-connected 40px
extern const lv_image_dsc_t ss_ic_lan;   // lan 40px
extern const lv_image_dsc_t ss_ic_browser;   // google-chrome 40px
extern const lv_image_dsc_t ss_ic_ok;   // check-circle 26px
extern const lv_image_dsc_t ss_ic_warn;   // alert-circle 26px
extern const lv_image_dsc_t ss_ic_fail;   // close-circle 26px
extern const lv_image_dsc_t ss_ic_todo;   // circle-outline 26px
extern const lv_image_dsc_t ss_ic_chev;   // chevron-right 26px
extern const lv_image_dsc_t ss_ic_back;   // arrow-left 26px
extern const lv_image_dsc_t ss_ic_refresh;   // refresh 26px
extern const lv_image_dsc_t ss_ic_cog;   // cog 26px
extern const lv_image_dsc_t ss_ic_download;   // download 26px
extern const lv_image_dsc_t ss_ic_shield;   // shield-check 26px
extern const lv_image_dsc_t ss_ic_swipe;   // gesture-swipe-right 40px
extern const lv_image_dsc_t ss_ic_help;   // help-circle 26px
extern const lv_image_dsc_t ss_ic_lock;   // lock 26px
extern const lv_image_dsc_t ss_ic_play;   // play-circle 40px
extern const lv_image_dsc_t ss_ic_unlink;   // link-variant-off 26px
extern const lv_image_dsc_t ss_ic_cur;   // play-circle 26px

#ifdef __cplusplus
}
#endif
