// Generated by tools/gen_recovery_assets.py - do not edit.
#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t offset;   // into the font's alpha bitmap
    uint8_t  w, h;
    int8_t   x, y;     // top-left relative to the pen (x) and the line top (y)
    uint8_t  adv;
} rec_glyph_t;

typedef struct {
    const rec_glyph_t *glyphs;
    const uint8_t     *bits;    // 8-bit alpha, row-major per glyph
    uint8_t            line_h;
    uint8_t            ascent;
    uint8_t            first, last;
} rec_font_t;

typedef struct {
    const uint8_t *rgba;        // R, G, B, A per pixel
    uint16_t       w, h;
} rec_image_t;

extern const rec_font_t rec_font_title;
extern const rec_font_t rec_font_body;
extern const rec_font_t rec_font_small;
extern const rec_image_t rec_logo;

#ifdef __cplusplus
}
#endif
