// AUTO-GENERATED by tools/gen_icons.py — do not edit.
// Color launcher/app icons (icons8 flat-color, MIT) as LVGL 9 ARGB8888.
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t nv_icon_settings;
extern const lv_image_dsc_t nv_icon_files;
extern const lv_image_dsc_t nv_icon_anima;
extern const lv_image_dsc_t nv_icon_diag;
extern const lv_image_dsc_t nv_icon_terminal;
extern const lv_image_dsc_t nv_icon_gallery;
extern const lv_image_dsc_t nv_icon_music;
extern const lv_image_dsc_t nv_icon_camera;
extern const lv_image_dsc_t nv_icon_calc;
extern const lv_image_dsc_t nv_icon_tasks;
extern const lv_image_dsc_t nv_icon_notes;
extern const lv_image_dsc_t nv_icon_apps;
extern const lv_image_dsc_t nv_icon_wasm;
extern const lv_image_dsc_t nv_icon_screen;
extern const lv_image_dsc_t nv_icon_video;
extern const lv_image_dsc_t nv_icon_recorder;
extern const lv_image_dsc_t nv_icon_sysmon;

#ifdef __cplusplus
}
#endif
