// AUTO-GENERATED by tools/gen_icons.py — do not edit.
// Launcher/app icons, 80x80 LVGL 9 ARGB8888. The descriptors live in PSRAM and are empty until
// nv_icons_init() inflates them: call it once at boot, before any UI uses an icon.
#pragma once
#include <stdbool.h>
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern lv_image_dsc_t nv_icon_settings;
extern lv_image_dsc_t nv_icon_files;
extern lv_image_dsc_t nv_icon_anima;
extern lv_image_dsc_t nv_icon_diag;
extern lv_image_dsc_t nv_icon_terminal;
extern lv_image_dsc_t nv_icon_gallery;
extern lv_image_dsc_t nv_icon_music;
extern lv_image_dsc_t nv_icon_camera;
extern lv_image_dsc_t nv_icon_calc;
extern lv_image_dsc_t nv_icon_tasks;
extern lv_image_dsc_t nv_icon_notes;
extern lv_image_dsc_t nv_icon_apps;
extern lv_image_dsc_t nv_icon_wasm;
extern lv_image_dsc_t nv_icon_screen;
extern lv_image_dsc_t nv_icon_video;
extern lv_image_dsc_t nv_icon_recorder;
extern lv_image_dsc_t nv_icon_sysmon;
extern lv_image_dsc_t nv_icon_wtimer;
extern lv_image_dsc_t nv_icon_wtorch;
extern lv_image_dsc_t nv_icon_wpiano;
extern lv_image_dsc_t nv_icon_wcannon;
extern lv_image_dsc_t nv_icon_wtank;
extern lv_image_dsc_t nv_icon_wabc;
extern lv_image_dsc_t nv_icon_wcode;
extern lv_image_dsc_t nv_icon_wgame;
extern lv_image_dsc_t nv_icon_wbug;

// Inflate every icon into PSRAM (idempotent). False if memory was short or an icon failed
// to decode; the icons that did decode are usable either way.
bool nv_icons_init(void);

#ifdef __cplusplus
}
#endif
