"""angler_mask.py - Vertice Bass: the angler's silhouette for the 2D fishing line.

The line is drawn over the 3D frame, so where it runs behind the angler (the cast and the lure out
on the water sit right behind him from the boat camera) it must not cross his body. This reads the
four billboard poses (img/an_*.565: keyed magenta, row 0 at the bottom), drops the thin rod with a
morphological opening, and writes a 32x32 coverage mask per pose to angler_mask.h
(bit c of row r = column c of the r-th row from the TOP).

    python apps/bass/art/angler_mask.py
"""
import os
import struct

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.join(HERE, "..")
POSES = ("an_idle", "an_wind", "an_cast", "an_reel")   # same order as g_angler / angler.h
N = 32


def load565(path):
    with open(path, "rb") as f:
        w, h = struct.unpack("<HH", f.read(4))
        px = np.frombuffer(f.read(w * h * 2), dtype="<u2").reshape(h, w)
    return px


def erode(m, r):
    out = m.copy()
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            out &= np.roll(np.roll(m, dy, 0), dx, 1)
    return out


def dilate(m, r):
    out = m.copy()
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            out |= np.roll(np.roll(m, dy, 0), dx, 1)
    return out


rows = []
for n in POSES:
    px = load565(os.path.join(APP, "img", n + ".565"))[::-1]   # billboard rows are bottom-up
    solid = px != 0xF81F
    body = dilate(erode(solid, 3), 3)                           # the rod (a few px wide) goes
    h, w = body.shape
    cov = body.reshape(N, h // N, N, w // N).mean(axis=(1, 3))
    m = cov > 0.35
    rows.append([sum(1 << c for c in range(N) if m[r, c]) for r in range(N)])
    print(n, "".join("#" if m[r, c] else "." for r in (8, 16, 24) for c in range(N)))

with open(os.path.join(APP, "angler_mask.h"), "w", newline="\n") as f:
    f.write("// angler_mask.h - generated by art/angler_mask.py: each pose's body (no rod) on a 32x32 grid\n")
    f.write("// over its billboard square; bit c of row r = column c, row 0 at the TOP.\n")
    f.write("static const uint32_t k_angler_mask[4][32] = {\n")
    for r in rows:
        f.write("    { " + ", ".join("0x%08Xu" % v for v in r) + " },\n")
    f.write("};\n")
print("angler_mask.h written")
