#!/usr/bin/env python3
"""digits.py - Vertice Bass: the arcade readouts (clock, line out, weights) in the Fisherman's Bait
manner — bold slanted digits with a thick dark outline and a white face the game tints (red clock,
yellow weights, green totals) through nv_gfx_sprite's tint. Tabular: every digit has the same width.

Cells "0123456789.:-" in img/dg.565 (magenta-keyed); digits.h has each cell's x and width.
Montserrat Bold (SIL OFL). Run from the repo root:  python apps/bass/art/digits.py
"""
import os
import struct

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
FONT = os.path.join(HERE, "..", "..", "..", "managed_components", "lvgl__lvgl", "tests", "src", "test_files",
                    "fonts", "Montserrat-Bold.ttf")
S = 4
PX = 30                    # font size on the canvas
CH = 34                    # cell height
SL = 0.20                  # slant
OUTW = 2                   # outline, px


def render(ch, w):
    f = ImageFont.truetype(FONT, PX * S)
    W, H = w * S, CH * S
    m = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(m)
    l, t, r, b = f.getbbox(ch)
    l0, t0, r0, b0 = f.getbbox("0")                 # every glyph sits on the digits' baseline
    lean = SL * H
    x = (W - lean - (r - l)) / 2 - l
    y = (H - (b0 - t0)) / 2 - t0
    d.text((x, y), ch, font=f, fill=255)
    m = m.transform(m.size, Image.AFFINE, (1, SL, -SL * H, 0, 1, 0), resample=Image.BILINEAR)
    o = m.filter(ImageFilter.MaxFilter(2 * OUTW * S + 1))
    down = lambda im: np.asarray(im, np.float32).reshape(CH, S, w, S).mean(axis=(1, 3)) / 255
    c, ol = down(m), down(o)
    img = np.zeros((CH, w, 3), np.uint8)
    img[:] = (255, 0, 255)
    shade = np.linspace(1.0, 0.78, CH)
    for yy in range(CH):
        for xx in range(w):
            if ol[yy, xx] < 0.5:
                continue
            fv = c[yy, xx]
            v = int((255 * shade[yy]) * fv + 12 * (1 - fv))
            img[yy, xx] = (v, v, v)
    return Image.fromarray(img)


def main():
    chars = "0123456789.:-"
    f = ImageFont.truetype(FONT, PX)
    dw = int(max(f.getlength(c) for c in "0123456789") + SL * CH + 2 * OUTW + 2)
    widths = [dw if c not in ".:" else 12 for c in chars]
    cells = [render(c, w) for c, w in zip(chars, widths)]
    W = 512
    atlas = Image.new("RGB", (W, 64), (255, 0, 255))
    xs, x = [], 0
    for im in cells:
        atlas.paste(im, (x, 0))
        xs.append(x)
        x += im.width + 1
    a = np.asarray(atlas).astype(np.uint16)
    v = ((a[..., 0] & 0xF8) << 8) | ((a[..., 1] & 0xFC) << 3) | (a[..., 2] >> 3)
    with open(os.path.join(APP, "img", "dg.565"), "wb") as fh:
        fh.write(struct.pack("<HH", W, 64))
        fh.write(v.astype("<u2").tobytes())
    atlas.crop((0, 0, x, CH)).resize((x * 3, CH * 3), Image.NEAREST).save(os.path.join(os.environ.get("TEMP", "/tmp"), "digits_prev.png"))
    with open(os.path.join(APP, "digits.h"), "w", newline="\n") as fh:
        fh.write("// digits.h - generated by art/digits.py: slanted digit cells in img/dg.565 (\"0123456789.:-\").\n")
        fh.write("#define DG_H %d\n" % CH)
        fh.write("static const short k_dg_x[13] = { %s };\n" % ", ".join(str(v) for v in xs))
        fh.write("static const unsigned char k_dg_w[13] = { %s };\n" % ", ".join(str(v) for v in widths))
    print("dg.565 ok, digit width", dw)


if __name__ == "__main__":
    main()
