#!/usr/bin/env python3
"""font.py - Vertice Bass: the game's lettering as bitmap-font atlases for nv_gfx_sprite (ABI 15).

Montserrat Bold (SIL Open Font License, shipped with LVGL in managed_components) rendered in three
sizes for the 512x300 canvas. Each glyph: a white fill shading to light grey toward the bottom, a dark
outline anti-aliased against the fill, and a one-pixel drop shadow; magenta (0xF81F) around it. The
game tints the white with nv_gfx_sprite's tint argument, so one atlas draws every colour.

Writes img/fs.565, img/fm.565, img/fl.565 and fontx.h (per glyph: atlas x, y, w, h, the offset of
the cell from the pen position, and the advance). Run from the repo root:

    python apps/bass/art/font.py
"""
import os
import struct

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
FONT = os.path.join(HERE, "..", "..", "..", "managed_components", "lvgl__lvgl", "tests", "src", "test_files",
                    "fonts", "Montserrat-Bold.ttf")
SIZES = [("fs", 11, 1), ("fm", 17, 1), ("fl", 32, 2)]     # name, pixel size, outline width
CHARS = [chr(c) for c in range(32, 127)]
KEY = (255, 0, 255)


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def glyph(font, ch, ow):
    """RGB image of one glyph with outline + shadow on magenta, and its metrics."""
    S = 4                                                   # supersampling for the anti-aliasing
    big = ImageFont.truetype(FONT, font.size * S)
    l, t, r, b = big.getbbox(ch)
    adv = big.getlength(ch) / S            # unhinted: small sizes keep the real spacing
    pad = (ow + 2) * S
    w = max(1, r - l) + 2 * pad
    h = max(1, b - t) + 2 * pad
    m = Image.new("L", (w, h), 0)
    ImageDraw.Draw(m).text((pad - l, pad - t), ch, font=big, fill=255)
    fill = np.asarray(m, dtype=np.float32) / 255.0
    outline = np.asarray(m.filter(ImageFilter.MaxFilter(2 * ow * S + 1)), dtype=np.float32) / 255.0
    # down to the real size (box filter = coverage)
    def down(a):
        hh, ww = a.shape[0] // S, a.shape[1] // S
        return a[:hh * S, :ww * S].reshape(hh, S, ww, S).mean(axis=(1, 3))
    f, o = down(fill), down(outline)
    hh, ww = f.shape
    sh = np.zeros((hh + 1, ww + 1), np.float32)              # shadow: the outline moved by (1,1)
    sh[1:, 1:] = o
    img = np.zeros((hh + 1, ww + 1, 3), np.uint8)
    img[:] = KEY
    shade = np.linspace(1.0, 0.80, hh)[:, None]               # light top, a touch darker at the foot
    for y in range(hh + 1):
        for x in range(ww + 1):
            ov = o[y, x] if y < hh and x < ww else 0.0
            fv = f[y, x] if y < hh and x < ww else 0.0
            if ov >= 0.5:
                g = int(255 * shade[min(y, hh - 1), 0] * fv)
                d = 10                                         # the outline colour (near black)
                v = int(g + d * (1 - fv))
                img[y, x] = (v, v, v)
            elif sh[y, x] >= 0.5:
                img[y, x] = (6, 8, 14)
    # cell offset from the pen (left of the advance box, top of the line box at the font's ascent)
    asc = font.getmetrics()[0]
    xoff = l / S - pad / S
    yoff = t / S - pad / S
    return Image.fromarray(img), xoff, yoff, adv, asc


def main():
    out_h = ["// fontx.h - generated by art/font.py (Montserrat Bold, OFL): do not edit.",
             "// Per atlas: glyphs 32..126 {atlas x, y, w, h, cell offset x, y from the pen, advance in 1/4 px},",
             "// then the line height and the ascent.",
             "typedef struct { short x, y; unsigned char w, h; signed char ox, oy; unsigned char adv; } Glyph;"]
    for name, px, ow in SIZES:
        font = ImageFont.truetype(FONT, px)
        cells = [glyph(font, c, ow) for c in CHARS]
        W = 512
        x = y = rowh = 0
        place = []
        for im, *_ in cells:
            if x + im.width > W:
                x, y, rowh = 0, y + rowh + 1, 0
            place.append((x, y))
            x += im.width + 1
            rowh = max(rowh, im.height)
        H = y + rowh
        Hp = 8
        while Hp < H:
            Hp *= 2
        atlas = Image.new("RGB", (W, Hp), KEY)
        for (im, *_), (px_, py_) in zip(cells, place):
            atlas.paste(im, (px_, py_))
        a = np.asarray(atlas).astype(np.uint16)
        v = ((a[..., 0] & 0xF8) << 8) | ((a[..., 1] & 0xFC) << 3) | (a[..., 2] >> 3)
        with open(os.path.join(APP, "img", name + ".565"), "wb") as f:
            f.write(struct.pack("<HH", W, Hp))
            f.write(v.astype("<u2").tobytes())
        atlas.save(os.path.join(os.environ.get("TEMP", "/tmp"), name + "_atlas.png"))
        asc, desc = font.getmetrics()
        out_h.append("static const Glyph k_%s[95] = {" % name)
        rows = []
        for (im, xoff, yoff, adv, _), (px_, py_) in zip(cells, place):
            rows.append("{%d,%d,%d,%d,%d,%d,%d}" % (px_, py_, im.width, im.height, round(xoff), round(yoff), round(adv * 4)))
        for i in range(0, 95, 8):
            out_h.append("    " + ", ".join(rows[i:i + 8]) + ",")
        out_h.append("};")
        out_h.append("#define %s_LINE %d" % (name.upper(), asc + desc))
        out_h.append("#define %s_ASC %d" % (name.upper(), asc))
        print(name, W, "x", Hp, "line", asc + desc)
    with open(os.path.join(APP, "fontx.h"), "w", newline="\n") as f:
        f.write("\n".join(out_h) + "\n")


if __name__ == "__main__":
    main()
