"""lang.py - Vertice Bass: Spanish, French and German for the game's text.

The game speaks Italian and English in its sources (T(it, en) and the it/en tables). For the
three other languages of NucleoOS, T() looks the ENGLISH string up in lang.h, written here from
TR below. Run after changing any text in the game:

    python apps/bass/art/lang.py          # writes lang.h; lists English strings with no translation

Text is upper case (the game draws capitals); accented capitals are in the font atlases
(art/font.py), so write them as they are (É, Ñ, Ü, ß...).
"""
import os
import re
import sys

APP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SOURCES = ("main.c", "fish.c", "lake.c")

LIT = r'"((?:[^"\\]|\\.)*)"'


def extract():
    """Every English string the game can show, in source order."""
    out = []

    def add(s):
        if s and s not in out:
            out.append(s)
    for name in SOURCES:
        src = open(os.path.join(APP, name), encoding="utf-8").read()
        for m in re.finditer(r"\bT\(\s*" + LIT + r"\s*,\s*" + LIT + r"\s*\)", src):
            add(m.group(2))
        for m in re.finditer(r"\b(?:en|d_en|h_en|jen|g_lure_en)\s*\[[^\]]*\]\s*=\s*\{([^}]*)\}", src):
            for s in re.findall(LIT, m.group(1)):
                add(s)
        # species, stages, conditions: rows that open with an Italian and an English name
        if name in ("fish.c", "lake.c"):
            for m in re.finditer(r"\{\s*" + LIT + r"\s*,\s*" + LIT + r"\s*,\s*[\d.]", src):
                add(m.group(2))
        for m in re.finditer(r"\{\s*" + LIT + r"\s*,\s*" + LIT + r'\s*,\s*"\d\d:\d\d"', src):
            add(m.group(2))
        for m in re.finditer(r'\{\s*"intro\d"\s*,\s*\d+\s*,\s*\d+\s*,\s*\d\s*,\s*' + LIT + r"\s*,\s*" + LIT, src):
            add(m.group(2))
    return out


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lang_tr import TR   # English -> (Spanish, French, German)


def write(strings):
    rows = sorted((s, TR[s]) for s in strings if s in TR)
    with open(os.path.join(APP, "lang.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("// lang.h - generated by art/lang.py: do not edit. The game's text in Spanish, French and German,\n")
        f.write("// looked up by the English (sorted for a binary search): { en, es, fr, de }.\n")
        f.write("static const char *const k_tr[][4] = {\n")
        for en, (es, fr, de) in rows:
            q = lambda s: '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
            f.write("    { %s, %s, %s, %s },\n" % (q(en), q(es), q(fr), q(de)))
        f.write("};\n#define K_TR_N %d\n" % len(rows))
    return len(rows)


if __name__ == "__main__":
    strings = extract()
    if "--list" in sys.argv:
        for s in strings:
            print(s)
        sys.exit(0)
    missing = [s for s in strings if s not in TR]
    n = write(strings)
    print(f"lang.h: {n} strings; {len(missing)} without a translation")
    for s in missing:
        print("  missing:", s)
