// ANIMA L0 in natural language, Italian and English: the device-only rung (no model, no network) must
// keep understanding the ways people actually phrase a request — paraphrases, politeness, articles,
// punctuation, capitals — and must never leave the user with an empty reply. One table row per phrase;
// a regression prints the phrase and what L0 answered instead. Runs with the network mode OFF, as the
// "offline" setting on the device (docs/ANIMA_MODES.md).
#include "check.h"
#include <cstring>
#include <cstdlib>
#include <initializer_list>
extern "C" {
#include "nucleo_anima.h"
#include "anima_fakenet.h"
#include "anima_phrases.h"
}
#include "anima_phrases_cases.h"   // generated from tools/anima_phrases.txt
#include "anima_eval_cases.h"      // generated from the NucleoOS (Cardputer) ANIMA action corpora
extern "C" {
#include "anima_intent.h"
}
#include "anima_intent_golden.h"   // generated by tools/train_anima_intent.py

struct Case {
    const char *q;
    bool en;
    const char *intent;   // expected intent
    const char *arg;      // nullptr = any
    const char *reply;    // reply fragment, nullptr = any non-empty reply
};

// action-phrases.jsonl coverage reached when the import was added: raise it as L0 learns, never lower it.
static const int kCoverageFloor = 49;

static anima_result_t ask(const char *q, bool en)
{
    nucleo_anima_try_lock();
    anima_result_t r = nucleo_anima_query(q, en ? "en" : "it");
    nucleo_anima_unlock();
    return r;
}

static void run(const Case &c)
{
    const anima_result_t r = ask(c.q, c.en);
    const bool ok = !strcmp(r.intent, c.intent) && (!c.arg || !strcmp(r.arg, c.arg)) &&
                    r.reply[0] && (!c.reply || strstr(r.reply, c.reply));
    CHECK(ok);
    if (!ok) std::fprintf(stderr, "  [%s] %s -> intent=%s arg=%s reply=%s\n", c.en ? "en" : "it", c.q, r.intent, r.arg, r.reply);
}

static const Case kCases[] = {
    // ── greetings and small talk ──
    { "ciao",                                false, "greeting", nullptr, nullptr },
    { "buongiorno",                          false, "greeting", nullptr, nullptr },
    { "hello",                               true,  "greeting", nullptr, nullptr },
    { "grazie",                              false, "thanks",   nullptr, nullptr },
    { "thank you",                           true,  "thanks",   nullptr, nullptr },
    { "chi sei?",                            false, "whoami",   nullptr, "ANIMA" },
    { "who are you?",                        true,  "whoami",   nullptr, "ANIMA" },

    // ── time and date ──
    { "che ore sono?",                       false, "time", "time", nullptr },
    { "che ora è",                           false, "time", "time", nullptr },
    { "mi dici l'ora?",                      false, "time", "time", nullptr },
    { "what time is it?",                    true,  "time", "time", nullptr },
    { "che giorno è oggi?",                  false, "date", nullptr, nullptr },
    { "what day is it today?",               true,  "date", nullptr, nullptr },

    // ── maths ──
    { "quanto fa 17 per 23?",                false, "calc", nullptr, "391" },
    { "calcola la radice quadrata di 144",   false, "calc", nullptr, "12" },
    { "quanto fa (3+4)*2^3",                 false, "calc", nullptr, "56" },
    { "what is 12 times 12?",                true,  "calc", nullptr, "144" },
    { "square root of 81",                   true,  "calc", nullptr, "9" },

    // ── volume and brightness ──
    { "alza il volume",                      false, "set_volume", "+10", nullptr },
    { "abbassa il volume",                   false, "set_volume", "-10", nullptr },
    { "volume al 40%",                       false, "set_volume", "40",  nullptr },
    { "metti il volume a 25",                false, "set_volume", "25",  nullptr },
    { "turn the volume up",                  true,  "set_volume", "+10", nullptr },
    { "turn the volume down",                true,  "set_volume", "-10", nullptr },
    { "set the volume to 30",                true,  "set_volume", "30",  nullptr },
    { "luminosità al 70",                    false, "set_brightness", "70",  nullptr },
    { "abbassa la luminosità",               false, "set_brightness", "-10", nullptr },
    { "set brightness to 50",                true,  "set_brightness", "50",  nullptr },

    // ── apps: open / close ──
    { "apri le note",                        false, "open_app", "notes",    nullptr },
    { "apri la calcolatrice",                false, "open_app", "calc",     nullptr },
    { "apri impostazioni",                   false, "open_app", "settings", nullptr },
    { "puoi aprire la musica?",              false, "open_app", "music",    nullptr },
    { "Apri Le Note!",                       false, "open_app", "notes",    nullptr },
    { "open the calculator",                 true,  "open_app", "calc",     nullptr },
    { "open settings",                       true,  "open_app", "settings", nullptr },
    { "chiudi le note",                      false, "close_app", "notes",   nullptr },
    { "chiudi la musica",                    false, "close_app", "music",   nullptr },
    { "close the music",                     true,  "close_app", "music",   nullptr },

    // ── back to the home screen ──
    { "torna alla home",                     false, "go_home", nullptr, nullptr },
    { "vai alla home",                       false, "go_home", nullptr, nullptr },
    { "portami alla schermata principale",   false, "go_home", nullptr, nullptr },
    { "home",                                false, "go_home", nullptr, nullptr },
    { "chiudi tutto",                        false, "go_home", nullptr, nullptr },
    { "go home",                             true,  "go_home", nullptr, nullptr },
    { "go to the home screen",               true,  "go_home", nullptr, nullptr },
    { "close everything",                    true,  "go_home", nullptr, nullptr },

    // ── device status ──
    { "che ip hai?",                         false, "network", "network", nullptr },
    { "indirizzo ip",                        false, "network", "network", nullptr },
    { "qual è il tuo indirizzo ip?",         false, "network", "network", nullptr },
    { "qual è il tuo indirizzo ip",          false, "network", "network", nullptr },
    { "sei connesso al wifi?",               false, "network", "network", nullptr },
    { "what is your ip address?",            true,  "network", "network", nullptr },
    { "quanta memoria libera c'è?",          false, "ram",     "ram",     nullptr },
    { "quanto spazio libero ho sulla sd?",   false, "storage", "storage", nullptr },
    { "che versione hai?",                   false, "version", "version", nullptr },

    // ── timers, reminders, translation ──
    { "imposta un timer di 5 minuti",        false, "timer",     nullptr, "5 min" },
    { "metti un timer di 10 minuti",         false, "timer",     nullptr, "10 min" },
    { "ricordami di comprare il latte",      false, "add_event", nullptr, "comprare il latte" },
    { "traduci ciao in inglese",             false, "translate", nullptr, "ciao" },   // the dictionary lives on the SD

    // ── needs the internet: says so instead of guessing ──
    { "che tempo fa a Milano?",              false, "weather", nullptr, "internet" },

    // ── playback ──
    { "pausa",                               false, "media_pause",  nullptr, nullptr },
    { "metti in pausa la musica",            false, "media_pause",  nullptr, nullptr },
    { "riprendi la musica",                  false, "media_resume", nullptr, nullptr },
    { "continua la canzone",                 false, "media_resume", nullptr, nullptr },
    { "pause the song",                      true,  "media_pause",  nullptr, nullptr },
    { "resume",                              true,  "media_resume", nullptr, nullptr },
    { "riprendi",                            false, "media_resume", nullptr, nullptr },

    // ── direction words: "giù/su", and "troppo" turns the adjective into its opposite wish ──
    { "metti il volume più giù",             false, "set_volume",     "-10", nullptr },   // was +10 ("più")
    { "metti il volume più su",              false, "set_volume",     "+10", nullptr },
    { "il volume è troppo alto",             false, "set_volume",     "-10", nullptr },
    { "il volume è troppo basso",            false, "set_volume",     "+10", nullptr },
    { "lo schermo è troppo luminoso",        false, "set_brightness", "-10", nullptr },
    { "la luminosità è troppo bassa",        false, "set_brightness", "+10", nullptr },
    { "the volume is too loud",              true,  "set_volume",     "-10", nullptr },
    { "the screen is too dark",              true,  "set_brightness", "+10", nullptr },
    { "alza il volume",                      false, "set_volume",     "+10", nullptr },   // a verb still wins

    // ── double negation: a reminder, not a refusal ──
    { "don't forget the meeting tomorrow",   true,  "add_event", nullptr, nullptr },
    { "non dimenticare di chiamare Marco",   false, "add_event", nullptr, nullptr },
    { "don't open the music",                true,  "deny",      nullptr, nullptr },   // a real negation still refuses

    // ── ported from the NucleoOS (Cardputer) solver: offline world clock, holidays, Easter, hours between ──
    { "che ore sono a tokyo",                false, "worldclock", nullptr, "Tokyo" },
    { "what time is it in new york",         true,  "worldclock", nullptr, "New York" },
    { "quante ore ci sono tra le 9 e le 17:30", false, "date",    nullptr, "8 ore e 30 min" },   // was: the current time
    { "quando è pasquetta 2027",             false, "date",       nullptr, "29 marzo 2027" },
    { "when is easter 2030",                 true,  "date",       nullptr, "April 21, 2030" },
    { "quando è ferragosto 2030",            false, "date",       nullptr, "15 agosto 2030" },
    { "che giorno è il 25 dicembre 2026",    false, "date",       nullptr, "venerd" },

    // ── regressions found by probing the device ──
    { "apri il terminale",                   false, "open_app", "terminal", nullptr },   // was CLOSE ("termina"~"terminale")
    { "avvia il terminale",                  false, "open_app", "terminal", nullptr },
    { "show me the photos",                  true,  "open_app", "gallery",  nullptr },   // was weather ("p-hot-os")
    { "never mind",                          true,  "deny",     nullptr,    nullptr },   // was weather ("neve-r")
};

// A weather word INSIDE another word is no forecast: "p-hot-os", "neve-r", "hot-el", "t-rain", "s-cold".
static const char *const kNotWeather[] = {
    "cerco un hotel a Roma", "il treno delle 8", "mi hanno scolded", "never again", "show me the photos",
    "apri le foto", "solenne", "consoleggiato",
};

int main()
{
    if (system("rm -rf anima_sd && mkdir -p anima_sd/data/anima") != 0) return 1;
    CHECK(nucleo_anima_init("it") == ESP_OK);
    fakenet_online(0);
    nucleo_anima_set_net_mode(ANIMA_NET_OFF);

    for (const Case &c : kCases) run(c);

    for (const char *q : kNotWeather) {
        const anima_result_t r = ask(q, false);
        CHECK(strcmp(r.intent, "weather") != 0);
        if (!strcmp(r.intent, "weather")) std::fprintf(stderr, "  %s -> weather (should not)\n", q);
    }

    // NucleoOS action corpora. The curated eval_action set is a gate: the command runs, and a sentence that
    // only MENTIONS an action ("ho abbassato il volume ieri", "non aprire la musica") runs nothing. The raw
    // action-phrases set (partly machine-made) is a coverage metric: printed, and it may only grow.
    int eval_bad = 0, cov_ok = 0, cov_n = 0;
    for (const EvalCase &e : kEvalCases) {
        const anima_result_t r = ask(e.q, e.en);
        const bool acted = r.action == ANIMA_ACT_TOOL || r.action == ANIMA_ACT_LAUNCH || r.nsteps > 0;
        const bool ok = !strcmp(e.expect, "tier:none") ? !acted : !strcmp(r.intent, e.expect) ||
                        (r.nsteps > 0 && !strcmp(e.expect, "open_app") && r.action == ANIMA_ACT_LAUNCH);
        if (!e.strict) { cov_n++; cov_ok += ok; continue; }
        CHECK(ok);
        if (!ok && eval_bad++ < 40)
            std::fprintf(stderr, "  [%s] eval %s -> intent=%s action=%d (expect %s)\n", e.en ? "en" : "it", e.q, r.intent, (int)r.action, e.expect);
    }
    std::printf("       NucleoOS action-phrases coverage: %d/%d\n", cov_ok, cov_n);
    CHECK(cov_ok >= kCoverageFloor);   // a regression below what L0 understood when this was written

    // INTENT SUGGESTER. (1) C scores == the trainer's (tokenizer, features, hashing, int8 maths all mirrored).
    for (const IntentGolden &g : kIntentGolden) {
        float p = 0, p2 = 0;
        const int k = anima_intent_top(g.q, &p, &p2);
        const bool ok = k >= 0 && !strcmp(anima_intent_label[k], g.top) && p > g.p - 0.002f && p < g.p + 0.002f;
        CHECK(ok);
        if (!ok) std::fprintf(stderr, "  golden %s -> %s %.5f, trainer %s %.5f\n", g.q, k >= 0 ? anima_intent_label[k] : "?", p, g.top, g.p);
    }
    // (2) held-out phrasings it never saw: no fewer right, no more wrong, than when it was trained.
    {
        int right = 0, wrong = 0;
        for (const IntentHeld &h : kIntentHeld) {
            float p = 0;
            const char *s = anima_intent_suggest(h.q, h.en, &p);
            if (!s) continue;
            if (!strcmp(s, h.want)) right++;
            else wrong++;
            // whatever it offers, it never points the opposite way of the words said
            CHECK(anima_intent_compatible(h.q, s));
        }
        std::printf("       suggester held-out: %d right, %d wrong (floor %d, ceiling %d)\n", right, wrong, kHeldRightFloor, kHeldWrongCeil);
        CHECK(right >= kHeldRightFloor && wrong <= kHeldWrongCeil);
    }
    // (3) the whole loop on the engine: a sentence nobody understood -> "Intendi «X»?" -> "sì" runs X and
    // learns it -> the same sentence is then understood directly; "no" learns nothing.
    {
        const IntentHeld *pick = nullptr;
        for (const IntentHeld &h : kIntentHeld) {
            if (h.en || !strcmp(h.want, "-")) continue;
            const anima_result_t r = ask(h.q, false);
            if (!strcmp(r.intent, "suggest") && !strcmp(r.arg, h.want)) { pick = &h; break; }
            ask("no", false);   // drop whatever it offered
        }
        CHECK(pick != nullptr);
        if (pick) {
            const anima_result_t want = ask(pick->want, false);
            anima_result_t r = ask(pick->q, false);
            CHECK(!strcmp(r.intent, "suggest") && r.awaiting && strstr(r.reply, pick->want));
            r = ask("sì", false);
            CHECK(!strcmp(r.intent, want.intent) && !strcmp(r.arg, want.arg));
            r = ask(pick->q, false);                                // learned: no question any more
            CHECK(!strcmp(r.intent, want.intent) && !strcmp(r.arg, want.arg));
            if (strcmp(r.intent, want.intent)) std::fprintf(stderr, "  learned [%s] -> %s, want %s\n", pick->q, r.intent, want.intent);
            FILE *f = fopen("anima_sd/data/anima/phrases.user.tsv", "r");
            CHECK(f != nullptr);
            if (f) fclose(f);
        }
        // "no": an apology for the miss, nothing learned, nothing run
        for (const IntentHeld &h : kIntentHeld) {
            if (h.en || !strcmp(h.want, "-") || (pick && h.q == pick->q)) continue;
            anima_result_t r = ask(h.q, false);
            if (strcmp(r.intent, "suggest")) continue;
            r = ask("no", false);
            CHECK(!strcmp(r.intent, "deny") && r.action == ANIMA_ACT_ANSWER);
            r = ask(h.q, false);
            CHECK(!strcmp(r.intent, "suggest"));                    // still only a suggestion: not learned
            ask("no", false);
            break;
        }
        // an unrelated answer drops the offer: "che ore sono" after a suggestion is just the time
        for (const IntentHeld &h : kIntentHeld) {
            if (h.en || !strcmp(h.want, "-")) continue;
            if (strcmp(ask(h.q, false).intent, "suggest")) continue;
            CHECK(!strcmp(ask("che ore sono", false).intent, "time"));
            CHECK(strcmp(ask("sì", false).intent, h.want) != 0);   // the offer is gone
            break;
        }
    }

    // PARAPHRASES: every phrase in tools/anima_phrases.txt answers exactly like its canonical, and the
    // canonical itself is understood (a typo in a canonical would silently make its whole group dead).
    CHECK(anima_phrase_count() == (int)(sizeof kPhraseCases / sizeof kPhraseCases[0]));
    int para_bad = 0;
    for (const PhraseCase &pc : kPhraseCases) {
        const anima_result_t want = ask(pc.canon, pc.en);
        const anima_result_t got  = ask(pc.phrase, pc.en);
        const bool ok = want.tier != ANIMA_TIER_NONE && !strcmp(got.intent, want.intent) &&
                        !strcmp(got.arg, want.arg) && got.action == want.action && got.reply[0];
        CHECK(ok);
        if (!ok && para_bad++ < 40)
            std::fprintf(stderr, "  [%s] \"%s\" -> %s/%s, but \"%s\" -> %s/%s (tier %d)\n", pc.en ? "en" : "it",
                         pc.phrase, got.intent, got.arg, pc.canon, want.intent, want.arg, (int)want.tier);
    }

    // A miss is honest AND useful: never an empty reply, never an action, and it says what works.
    for (const char *q : { "raccontami una barzelletta", "asdkjh qwe zzz", "fammi un caffè" }) {
        const anima_result_t r = ask(q, false);
        const bool ok = r.action == ANIMA_ACT_NONE && r.reply[0] && strstr(r.reply, "Non lo so");
        CHECK(ok);
        if (!ok) std::fprintf(stderr, "  [it] %s -> intent=%s action=%d reply=%s\n", q, r.intent, (int)r.action, r.reply);
    }
    for (const char *q : { "tell me a joke", "qwzx plorp" }) {
        const anima_result_t r = ask(q, true);
        const bool ok = r.action == ANIMA_ACT_NONE && r.reply[0] && strstr(r.reply, "I don't know");
        CHECK(ok);
        if (!ok) std::fprintf(stderr, "  [en] %s -> intent=%s action=%d reply=%s\n", q, r.intent, (int)r.action, r.reply);
    }

    // "home" alone is the launcher, but Home Assistant and the home folder are not.
    for (const char *q : { "accendi la luce in home assistant", "apri la cartella home" }) {
        const anima_result_t r = ask(q, false);
        CHECK(strcmp(r.intent, "go_home") != 0);
        if (!strcmp(r.intent, "go_home")) std::fprintf(stderr, "  [it] %s -> go_home (should not)\n", q);
    }
    // "home" inside a plan: after closing something it is fine, next to opening an app it contradicts
    {
        anima_result_t p = ask("chiudi la musica e torna alla home", false);
        const bool ok = p.nsteps >= 1 && p.reply[0] &&
                        ((!strcmp(p.intent, "close_app") && !strcmp(p.steps[0].intent, "go_home")) ||
                         (!strcmp(p.intent, "plan") && p.nsteps == 2 && !strcmp(p.steps[1].intent, "go_home")));
        CHECK(ok);
        if (!ok) std::fprintf(stderr, "  [it] chiudi la musica e torna alla home -> intent=%s nsteps=%d reply=%s\n", p.intent, p.nsteps, p.reply);
        p = ask("apri le note e torna alla home", false);
        CHECK(!strcmp(p.intent, "plan_partial") && p.nsteps == 0 && p.reply[0]);
        if (strcmp(p.intent, "plan_partial")) std::fprintf(stderr, "  [it] apri le note e torna alla home -> intent=%s\n", p.intent);
    }
    {   // Easter without a year: the next one, and always a Sunday (a rollover bug once said "martedì")
        const anima_result_t e = ask("quando è pasqua", false);
        CHECK(!strcmp(e.intent, "date") && strstr(e.reply, "domenica"));
        if (!strstr(e.reply, "domenica")) std::fprintf(stderr, "  quando è pasqua -> %s\n", e.reply);
    }
    // a foreign network is still not the device's own ("l'ip del paradiso")
    CHECK(strcmp(ask("qual è l'indirizzo ip del server di google", false).intent, "network") != 0);

    system("rm -rf anima_sd");
    return TEST_DONE("anima_nl");
}
