"""embed_data.py <src dir> <out.h> <file>... — GNU units data files as C arrays (see nv_units_shim.c)."""
import os
import sys

src, out, names = sys.argv[1], sys.argv[2], sys.argv[3:]
with open(out, "w", newline="\n") as f:
    f.write("// generated by ports/cli/units/embed_data.py - do not edit\n#include <stddef.h>\n")
    for i, n in enumerate(names):
        b = open(os.path.join(src, n), "rb").read()
        f.write(f"static const unsigned char nv_ud{i}[{len(b)}] = {{")
        f.write(",".join(str(x) for x in b))
        f.write("};\n")
    f.write("struct nv_udata { const char *file; const unsigned char *data; size_t len; };\n")
    f.write("static const struct nv_udata nv_udata[] = {\n")
    for i, n in enumerate(names):
        f.write(f'    {{ "{n}", nv_ud{i}, sizeof nv_ud{i} }},\n')
    f.write("};\n")
    f.write(f"#define NV_UDATA_COUNT {len(names)}\n")
