// Second Screen wizard strings (EN, IT, ES, FR, DE — nv_lang_t order). Kept next to the app so the
// wizard's long guidance text doesn't bloat the shared nv_i18n catalog. Latin-1 only: the UI fonts
// have no glyphs beyond it (no ellipsis/em-dash/curly quotes).
#pragma once
#include "nv_i18n.h"

enum SsStr {
    S_HOME_TITLE, S_HOME_SUB, S_NET_NONE, S_NET_WIFI, S_NET_ETH, S_USB_HOST, S_USB_WAIT, S_USB_PC, S_USB_LIVE,
    S_OS_WIN, S_OS_MAC, S_OS_LINUX, S_OS_ANDROID, S_OS_OTHER,
    S_BEST_WIN, S_BEST_MAC, S_BEST_LINUX, S_BEST_ANDROID, S_BEST_OTHER,
    S_RECENT, S_OPTIONS, S_METHODS_TITLE, S_METHODS_SUB,
    S_M_USB, S_M_USB_D, S_M_CAST, S_M_CAST_D, S_M_MACVNC, S_M_MACVNC_D, S_M_VNC, S_M_VNC_D, S_M_ANDROID, S_M_ANDROID_D,
    S_B_BEST, S_B_EXT, S_B_MIRROR, S_B_TOUCH, S_B_NOINST, S_B_ONCE,
    S_ST_READY, S_ST_ACTION, S_ST_LIVE, S_ST_FAIL, S_ST_WAIT,
    S_U1, S_U1_D, S_U1_BTN, S_U1_PENDING, S_REBOOT, S_U2, S_U2_D, S_U3, S_U3_D, S_U3_FAIL, S_U4, S_U4_D,
    S_C1, S_C1_D, S_C1_BTN, S_C2, S_C2_D, S_C3, S_C3_D, S_C3_WAIT,
    S_V_MAC1, S_V_MAC1_D, S_V_SRV, S_V_SRV_WIN, S_V_SRV_LINUX, S_A1, S_A1_D,
    S_V_CONN, S_V_CONN_D, S_V_FOUND, S_V_SEARCHING, S_V_NONE, S_V_HOST, S_V_PASS, S_V_CONNECT, S_V_REVERSE,
    S_V_ERR_CONNECT, S_V_ERR_PROTOCOL, S_V_ERR_SECURITY, S_V_ERR_AUTH, S_V_ERR_NEEDPW, S_V_ERR_CLOSED, S_V_ERR_MEMORY,
    S_V_CONNECTING, S_V_SEARCH_AGAIN,
    S_NEXT, S_NEXT_NOW, S_OTHER_DEVICE,
    S_PAUSED, S_PAUSED_D, S_RESUME, S_DISCONNECT, S_SWIPE_HINT, S_ENDED,
    S_ASK_T, S_ASK_D, S_ASK_ONCE, S_ASK_ALWAYS, S_ASK_DENY,
    S_OPT_AUTO, S_OPT_ASK, S_OPT_FORGET, S_OPT_FORGOT, S_OPT_USB, S_OPT_USB_PC, S_OPT_USB_ACC, S_OPT_REBOOT_NOTE, S_DONE,
    S_STEP_OF, S_LIVE_WITH, S_V_USER, S_V_MAC_ALT,
    S_SUG_USB_NODRV, S_SUG_NO_NET, S_SUG_VNC_FAIL, S_SUG_CAST_WAIT, S_SUG_DRIVER, S_SUG_WIFI, S_SUG_RETRY, S_SUG_OPEN, S_DONE_NEXT, S_QUICK, S_OPT_FORGET_RECENT,
    S_COUNT
};

// clang-format off
struct SsRow { SsStr id; const char *t[NV_LANG_COUNT]; };
static constexpr SsRow kSsRows[] = {
{S_HOME_TITLE, {"Connect a device", "Collega un dispositivo", "Conecta un dispositivo", "Connecter un appareil", "Gerät verbinden"}},
{S_HOME_SUB, {"Pick what you want to show here: the board guides you step by step and checks each step by itself.",
                "Scegli cosa vuoi mostrare qui: la scheda ti guida passo passo e controlla da sola ogni passaggio.",
                "Elige qué quieres mostrar aquí: la placa te guía paso a paso y comprueba cada paso sola.",
                "Choisissez ce que vous voulez afficher ici : la carte vous guide pas à pas et vérifie chaque étape.",
                "Wähle, was hier angezeigt werden soll: das Board führt dich Schritt für Schritt und prüft jeden Schritt selbst."}},
{S_NET_NONE, {"Network: not connected", "Rete: non collegata", "Red: no conectada", "Réseau : non connecté", "Netzwerk: nicht verbunden"}},
{S_NET_WIFI, {"Wi-Fi %s", "Wi-Fi %s", "Wi-Fi %s", "Wi-Fi %s", "WLAN %s"}},
{S_NET_ETH, {"Ethernet %s", "Ethernet %s", "Ethernet %s", "Ethernet %s", "Ethernet %s"}},
{S_USB_HOST, {"USB: accessories mode", "USB: modalità accessori", "USB: modo accesorios", "USB : mode accessoires", "USB: Zubehörmodus"}},
{S_USB_WAIT, {"USB: ready for a PC", "USB: pronta per il PC", "USB: lista para el PC", "USB : prête pour un PC", "USB: bereit für PC"}},
{S_USB_PC, {"USB: PC connected", "USB: PC collegato", "USB: PC conectado", "USB : PC connecté", "USB: PC verbunden"}},
{S_USB_LIVE, {"USB: live", "USB: attivo", "USB: activo", "USB : actif", "USB: aktiv"}},
{S_OS_WIN, {"Windows", "Windows", "Windows", "Windows", "Windows"}},
{S_OS_MAC, {"Mac", "Mac", "Mac", "Mac", "Mac"}},
{S_OS_LINUX, {"Linux", "Linux", "Linux", "Linux", "Linux"}},
{S_OS_ANDROID, {"Android", "Android", "Android", "Android", "Android"}},
{S_OS_OTHER, {"Other", "Altro", "Otro", "Autre", "Andere"}},
{S_BEST_WIN, {"USB cable", "Cavo USB", "Cable USB", "Câble USB", "USB-Kabel"}},
{S_BEST_MAC, {"Screen Sharing", "Condivisione schermo", "Compartir pantalla", "Partage d'écran", "Bildschirmfreigabe"}},
{S_BEST_LINUX, {"Browser", "Browser", "Navegador", "Navigateur", "Browser"}},
{S_BEST_ANDROID, {"droidVNC-NG app", "App droidVNC-NG", "App droidVNC-NG", "App droidVNC-NG", "App droidVNC-NG"}},
{S_BEST_OTHER, {"Any browser", "Qualsiasi browser", "Cualquier navegador", "Tout navigateur", "Jeder Browser"}},
{S_RECENT, {"Recent", "Recenti", "Recientes", "Récents", "Zuletzt"}},
{S_OPTIONS, {"Options", "Opzioni", "Opciones", "Options", "Optionen"}},
{S_METHODS_TITLE, {"%s: how to connect", "%s: come collegarlo", "%s: cómo conectarlo", "%s : comment le connecter", "%s: so verbindest du es"}},
{S_METHODS_SUB, {"Best first. If one doesn't work, the board suggests the next one.",
                   "In ordine dal migliore. Se uno non funziona, la scheda ti propone il successivo.",
                   "Del mejor al peor. Si uno no funciona, la placa te propone el siguiente.",
                   "Du meilleur au moins bon. Si l'un ne marche pas, la carte propose le suivant.",
                   "Das beste zuerst. Klappt eines nicht, schlägt das Board das nächste vor."}},
{S_M_USB, {"USB cable", "Cavo USB", "Cable USB", "Câble USB", "USB-Kabel"}},
{S_M_USB_D, {"Extended desktop, touch, up to 60 fps. One-time Windows driver.",
               "Schermo esteso, touch, fino a 60 fps. Driver Windows una volta sola.",
               "Escritorio extendido, táctil, hasta 60 fps. Driver de Windows una sola vez.",
               "Bureau étendu, tactile, jusqu'à 60 i/s. Pilote Windows une seule fois.",
               "Erweiterter Desktop, Touch, bis 60 fps. Windows-Treiber einmalig."}},
{S_M_CAST, {"Wi-Fi from the browser", "Wi-Fi dal browser", "Wi-Fi desde el navegador", "Wi-Fi depuis le navigateur", "WLAN aus dem Browser"}},
{S_M_CAST_D, {"Mirror a screen or a window. Nothing to install.",
                "Duplica uno schermo o una finestra. Niente da installare.",
                "Duplica una pantalla o una ventana. Nada que instalar.",
                "Duplique un écran ou une fenêtre. Rien à installer.",
                "Spiegelt einen Bildschirm oder ein Fenster. Nichts zu installieren."}},
{S_M_MACVNC, {"Mac Screen Sharing", "Condivisione schermo del Mac", "Compartir pantalla del Mac", "Partage d'écran du Mac", "Mac-Bildschirmfreigabe"}},
{S_M_MACVNC_D, {"Built into macOS. The board's touch controls the Mac.",
                  "Integrata in macOS. Il touch della scheda comanda il Mac.",
                  "Integrado en macOS. El táctil de la placa controla el Mac.",
                  "Intégré à macOS. Le tactile de la carte pilote le Mac.",
                  "In macOS integriert. Der Touch des Boards steuert den Mac."}},
{S_M_VNC, {"VNC", "VNC", "VNC", "VNC", "VNC"}},
{S_M_VNC_D, {"A VNC server on the computer (TightVNC, GNOME, KDE). Touch works as a mouse.",
               "Un server VNC sul computer (TightVNC, GNOME, KDE). Il touch fa da mouse.",
               "Un servidor VNC en el ordenador (TightVNC, GNOME, KDE). El táctil hace de ratón.",
               "Un serveur VNC sur l'ordinateur (TightVNC, GNOME, KDE). Le tactile sert de souris.",
               "Ein VNC-Server auf dem Computer (TightVNC, GNOME, KDE). Touch dient als Maus."}},
{S_M_ANDROID, {"droidVNC-NG", "droidVNC-NG", "droidVNC-NG", "droidVNC-NG", "droidVNC-NG"}},
{S_M_ANDROID_D, {"Free app: shows the phone here, with touch control.",
                   "App gratuita: mostra il telefono qui, con controllo touch.",
                   "App gratuita: muestra el teléfono aquí, con control táctil.",
                   "App gratuite : affiche le téléphone ici, avec contrôle tactile.",
                   "Kostenlose App: zeigt das Handy hier, mit Touch-Steuerung."}},
{S_B_BEST, {"Recommended", "Consigliato", "Recomendado", "Recommandé", "Empfohlen"}},
{S_B_EXT, {"Extended", "Esteso", "Extendido", "Étendu", "Erweitert"}},
{S_B_MIRROR, {"Mirror", "Duplica", "Duplica", "Duplique", "Spiegeln"}},
{S_B_TOUCH, {"Touch", "Touch", "Táctil", "Tactile", "Touch"}},
{S_B_NOINST, {"No install", "Niente da installare", "Sin instalar", "Sans installation", "Ohne Installation"}},
{S_B_ONCE, {"One-time setup", "Una volta sola", "Una sola vez", "Une seule fois", "Einmalig"}},
{S_ST_READY, {"Ready", "Pronto", "Listo", "Prêt", "Bereit"}},
{S_ST_ACTION, {"Needs a step", "Serve un passaggio", "Falta un paso", "Une étape à faire", "Ein Schritt fehlt"}},
{S_ST_LIVE, {"Connected", "Collegato", "Conectado", "Connecté", "Verbunden"}},
{S_ST_FAIL, {"Didn't work", "Non ha funzionato", "No funcionó", "N'a pas marché", "Hat nicht geklappt"}},
{S_ST_WAIT, {"Waiting", "In attesa", "Esperando", "En attente", "Warte"}},
{S_U1, {"USB port in PC mode", "Porta USB in modalità PC", "Puerto USB en modo PC", "Port USB en mode PC", "USB-Port im PC-Modus"}},
{S_U1_D, {"The high-speed USB-C works either with speakers and keyboards or with a PC. The screen needs PC mode: the board restarts once.",
            "La USB-C ad alta velocità funziona con casse e tastiere oppure con un PC. Per lo schermo serve la modalità PC: la scheda si riavvia una volta.",
            "El USB-C de alta velocidad funciona con altavoces y teclados o con un PC. La pantalla necesita el modo PC: la placa se reinicia una vez.",
            "L'USB-C haute vitesse sert aux enceintes et claviers ou à un PC. L'écran demande le mode PC : la carte redémarre une fois.",
            "Das Highspeed-USB-C arbeitet mit Lautsprechern und Tastaturen oder mit einem PC. Der Bildschirm braucht den PC-Modus: das Board startet einmal neu."}},
{S_U1_BTN, {"Switch to PC mode and restart", "Passa a modalità PC e riavvia", "Cambiar a modo PC y reiniciar", "Passer en mode PC et redémarrer", "PC-Modus aktivieren und neu starten"}},
{S_U1_PENDING, {"PC mode is set: restart to apply it.", "Modalità PC impostata: riavvia per applicarla.", "Modo PC elegido: reinicia para aplicarlo.", "Mode PC choisi : redémarrez pour l'appliquer.", "PC-Modus gewählt: zum Anwenden neu starten."}},
{S_REBOOT, {"Restart now", "Riavvia ora", "Reiniciar ahora", "Redémarrer", "Jetzt neu starten"}},
{S_U2, {"Plug the cable into the PC", "Collega il cavo al PC", "Conecta el cable al PC", "Branchez le câble au PC", "Kabel mit dem PC verbinden"}},
{S_U2_D, {"Use the board's high-speed USB-C (not the programming one) and a USB port on the PC, ideally without a hub. This step ticks itself as soon as the PC sees the board.",
            "Usa la USB-C ad alta velocità della scheda (non quella di programmazione) e una porta USB del PC, meglio senza hub. Il passo si spunta da solo appena il PC vede la scheda.",
            "Usa el USB-C de alta velocidad de la placa (no el de programación) y un puerto USB del PC, mejor sin hub. El paso se marca solo cuando el PC ve la placa.",
            "Utilisez l'USB-C haute vitesse de la carte (pas celui de programmation) et un port USB du PC, sans hub de préférence. L'étape se coche dès que le PC voit la carte.",
            "Nimm das Highspeed-USB-C des Boards (nicht das zum Programmieren) und einen USB-Port am PC, am besten ohne Hub. Der Schritt hakt sich ab, sobald der PC das Board sieht."}},
{S_U3, {"Driver (first time only)", "Driver (solo la prima volta)", "Driver (solo la primera vez)", "Pilote (la première fois)", "Treiber (nur beim ersten Mal)"}},
{S_U3_D, {"On the PC open this address and download the driver (or take it from the SD card: nucleos/drivers/windows). Click Install: it is signed, no test mode needed.",
            "Sul PC apri questo indirizzo e scarica il driver (oppure prendilo dalla SD: nucleos/drivers/windows). Premi Install: è firmato, niente modalità test.",
            "En el PC abre esta dirección y descarga el driver (o tómalo de la SD: nucleos/drivers/windows). Pulsa Install: está firmado, sin modo de prueba.",
            "Sur le PC ouvrez cette adresse et téléchargez le pilote (ou prenez-le sur la SD : nucleos/drivers/windows). Cliquez Install : il est signé, pas de mode test.",
            "Öffne am PC diese Adresse und lade den Treiber (oder von der SD: nucleos/drivers/windows). Auf Install klicken: er ist signiert, kein Testmodus nötig."}},
{S_U3_FAIL, {"The PC is connected but sends no picture: the driver is missing, or the computer isn't Windows.",
               "Il PC è collegato ma non manda immagini: manca il driver oppure il computer non è Windows.",
               "El PC está conectado pero no envía imagen: falta el driver o el ordenador no es Windows.",
               "Le PC est connecté mais n'envoie pas d'image : pilote absent, ou l'ordinateur n'est pas sous Windows.",
               "Der PC ist verbunden, sendet aber kein Bild: Treiber fehlt oder der Computer ist kein Windows-PC."}},
{S_U4, {"Extend the desktop", "Estendi il desktop", "Extiende el escritorio", "Étendez le bureau", "Desktop erweitern"}},
{S_U4_D, {"Press Win+P and choose Extend. The screen turns on with the first picture from Windows.",
            "Premi Win+P e scegli Estendi. Lo schermo si accende con la prima immagine da Windows.",
            "Pulsa Win+P y elige Extender. La pantalla se enciende con la primera imagen de Windows.",
            "Appuyez sur Win+P et choisissez Étendre. L'écran s'allume avec la première image de Windows.",
            "Win+P drücken und Erweitern wählen. Der Bildschirm geht mit dem ersten Bild von Windows an."}},
{S_C1, {"Board on the network", "Scheda in rete", "Placa en la red", "Carte sur le réseau", "Board im Netzwerk"}},
{S_C1_D, {"The board and the computer must be on the same network (Wi-Fi or network cable).",
            "Scheda e computer devono stare sulla stessa rete (Wi-Fi o cavo di rete).",
            "La placa y el ordenador deben estar en la misma red (Wi-Fi o cable de red).",
            "La carte et l'ordinateur doivent être sur le même réseau (Wi-Fi ou câble réseau).",
            "Board und Computer müssen im selben Netzwerk sein (WLAN oder Netzwerkkabel)."}},
{S_C1_BTN, {"Wi-Fi settings", "Impostazioni Wi-Fi", "Ajustes Wi-Fi", "Réglages Wi-Fi", "WLAN-Einstellungen"}},
{S_C2, {"Open the page on the computer", "Apri la pagina sul computer", "Abre la página en el ordenador", "Ouvrez la page sur l'ordinateur", "Seite am Computer öffnen"}},
{S_C2_D, {"In the computer's browser type this address (or scan the code):",
            "Nel browser del computer scrivi questo indirizzo (o inquadra il codice):",
            "En el navegador del ordenador escribe esta dirección (o escanea el código):",
            "Dans le navigateur de l'ordinateur tapez cette adresse (ou scannez le code) :",
            "Gib im Browser des Computers diese Adresse ein (oder scanne den Code):"}},
{S_C3, {"Share the screen", "Condividi lo schermo", "Comparte la pantalla", "Partagez l'écran", "Bildschirm teilen"}},
{S_C3_D, {"Click Share screen and pick a screen or a window. If the browser doesn't allow it, use \"Download NucleoCast\" on the page: it opens with a double click, no warnings.",
            "Premi Condividi schermo e scegli uno schermo o una finestra. Se il browser non lo permette usa \"Scarica NucleoCast\" nella pagina: si apre con un doppio clic, senza avvisi.",
            "Pulsa Compartir pantalla y elige una pantalla o ventana. Si el navegador no lo permite, usa \"Descargar NucleoCast\" en la página: se abre con doble clic, sin avisos.",
            "Cliquez sur Partager l'écran et choisissez un écran ou une fenêtre. Si le navigateur refuse, utilisez \"Télécharger NucleoCast\" : il s'ouvre d'un double clic, sans alerte.",
            "Auf Bildschirm teilen klicken und Bildschirm oder Fenster wählen. Erlaubt es der Browser nicht, \"NucleoCast herunterladen\" nutzen: per Doppelklick, ohne Warnungen."}},
{S_C3_WAIT, {"Computer connected: %s. Waiting for the share...", "Computer collegato: %s. In attesa della condivisione...", "Ordenador conectado: %s. Esperando...", "Ordinateur connecté : %s. En attente du partage...", "Computer verbunden: %s. Warte auf Freigabe..."}},
{S_V_MAC1, {"Turn on Screen Sharing", "Attiva Condivisione schermo", "Activa Compartir pantalla", "Activez le Partage d'écran", "Bildschirmfreigabe einschalten"}},
{S_V_MAC1_D, {"On the Mac: System Settings > General > Sharing > Screen Sharing. Then (i) > Computer Settings > \"VNC viewers may control screen with password\" and set a password.",
                "Sul Mac: Impostazioni di Sistema > Generali > Condivisione > Condivisione schermo. Poi (i) > Impostazioni computer > \"I visualizzatori VNC possono controllare lo schermo con la password\" e scegli una password.",
                "En el Mac: Ajustes del Sistema > General > Compartir > Compartir pantalla. Luego (i) > Ajustes del ordenador > \"Los visores VNC pueden controlar la pantalla con contraseña\" y elige una contraseña.",
                "Sur le Mac : Réglages Système > Général > Partage > Partage d'écran. Puis (i) > Réglages de l'ordinateur > \"Les utilisateurs VNC peuvent contrôler l'écran avec un mot de passe\".",
                "Am Mac: Systemeinstellungen > Allgemein > Teilen > Bildschirmfreigabe. Dann (i) > Computereinstellungen > \"VNC-Benutzer dürfen den Bildschirm mit Passwort steuern\"."}},
{S_V_SRV, {"Start a VNC server", "Avvia un server VNC", "Inicia un servidor VNC", "Lancez un serveur VNC", "VNC-Server starten"}},
{S_V_SRV_WIN, {"Install TightVNC Server (free) and set a password (max 8 characters).",
                 "Installa TightVNC Server (gratuito) e imposta una password (max 8 caratteri).",
                 "Instala TightVNC Server (gratis) y pon una contraseña (máx. 8 caracteres).",
                 "Installez TightVNC Server (gratuit) et définissez un mot de passe (8 caractères max).",
                 "TightVNC Server (kostenlos) installieren und ein Passwort setzen (max. 8 Zeichen)."}},
{S_V_SRV_LINUX, {"GNOME: Settings > Sharing > Remote Desktop (VNC). KDE: Desktop Sharing. Or run: x11vnc -forever -passwd PASSWORD",
                   "GNOME: Impostazioni > Condivisione > Desktop remoto (VNC). KDE: Condivisione desktop. Oppure: x11vnc -forever -passwd PASSWORD",
                   "GNOME: Ajustes > Compartir > Escritorio remoto (VNC). KDE: Compartir escritorio. O bien: x11vnc -forever -passwd CLAVE",
                   "GNOME : Paramètres > Partage > Bureau à distance (VNC). KDE : Partage du bureau. Ou : x11vnc -forever -passwd MOTDEPASSE",
                   "GNOME: Einstellungen > Freigabe > Entfernter Desktop (VNC). KDE: Arbeitsfläche freigeben. Oder: x11vnc -forever -passwd PASSWORT"}},
{S_A1, {"Install droidVNC-NG", "Installa droidVNC-NG", "Instala droidVNC-NG", "Installez droidVNC-NG", "droidVNC-NG installieren"}},
{S_A1_D, {"On the phone install droidVNC-NG (free, Play Store or F-Droid). Open it, set a password, grant the permissions and tap Start.",
            "Sul telefono installa droidVNC-NG (gratuito, Play Store o F-Droid). Aprilo, imposta una password, concedi i permessi e premi Start.",
            "En el teléfono instala droidVNC-NG (gratis, Play Store o F-Droid). Ábrelo, pon una contraseña, concede los permisos y pulsa Start.",
            "Sur le téléphone installez droidVNC-NG (gratuit, Play Store ou F-Droid). Ouvrez-le, définissez un mot de passe, accordez les autorisations et touchez Start.",
            "Installiere am Handy droidVNC-NG (kostenlos, Play Store oder F-Droid). Öffnen, Passwort setzen, Berechtigungen erteilen und Start tippen."}},
{S_V_CONN, {"Connect", "Collegati", "Conéctate", "Connectez-vous", "Verbinden"}},
{S_V_CONN_D, {"Tap a device found on the network, or type its address.",
                "Tocca un dispositivo trovato in rete, oppure scrivi il suo indirizzo.",
                "Toca un dispositivo encontrado en la red o escribe su dirección.",
                "Touchez un appareil trouvé sur le réseau, ou tapez son adresse.",
                "Tippe auf ein gefundenes Gerät oder gib seine Adresse ein."}},
{S_V_FOUND, {"Found on the network", "Trovati in rete", "Encontrados en la red", "Trouvés sur le réseau", "Im Netzwerk gefunden"}},
{S_V_SEARCHING, {"Searching...", "Cerco...", "Buscando...", "Recherche...", "Suche..."}},
{S_V_NONE, {"Nothing found yet: type the address above.", "Ancora nessuno: scrivi l'indirizzo qui sopra.", "Nada todavía: escribe la dirección arriba.", "Rien pour l'instant : tapez l'adresse ci-dessus.", "Noch nichts gefunden: Adresse oben eingeben."}},
{S_V_HOST, {"IP address", "Indirizzo IP", "Dirección IP", "Adresse IP", "IP-Adresse"}},
{S_V_PASS, {"Password", "Password", "Contraseña", "Mot de passe", "Passwort"}},
{S_V_CONNECT, {"Connect", "Collega", "Conectar", "Connecter", "Verbinden"}},
{S_V_REVERSE, {"Or from the device (reverse connection) to:", "Oppure dal dispositivo (connessione inversa) verso:", "O desde el dispositivo (conexión inversa) a:", "Ou depuis l'appareil (connexion inverse) vers :", "Oder vom Gerät aus (Reverse-Verbindung) zu:"}},
{S_V_ERR_CONNECT, {"Can't reach it: server off, wrong address or firewall.", "Non raggiungibile: server spento, indirizzo sbagliato o firewall.", "No se alcanza: servidor apagado, dirección errónea o firewall.", "Injoignable : serveur arrêté, mauvaise adresse ou pare-feu.", "Nicht erreichbar: Server aus, falsche Adresse oder Firewall."}},
{S_V_ERR_PROTOCOL, {"That's not a VNC server.", "Non è un server VNC.", "No es un servidor VNC.", "Ce n'est pas un serveur VNC.", "Das ist kein VNC-Server."}},
{S_V_ERR_SECURITY, {"The server wants a security mode the board lacks: turn on the VNC password option.", "Il server chiede una sicurezza non supportata: attiva l'opzione password VNC.", "El servidor pide una seguridad no soportada: activa la contraseña VNC.", "Le serveur exige une sécurité non prise en charge : activez le mot de passe VNC.", "Der Server verlangt eine nicht unterstützte Sicherheit: VNC-Passwort aktivieren."}},
{S_V_ERR_AUTH, {"Wrong password.", "Password sbagliata.", "Contraseña incorrecta.", "Mot de passe incorrect.", "Falsches Passwort."}},
{S_V_ERR_NEEDPW, {"This server needs a password.", "Questo server chiede una password.", "Este servidor pide contraseña.", "Ce serveur demande un mot de passe.", "Dieser Server braucht ein Passwort."}},
{S_V_ERR_CLOSED, {"The server closed the connection.", "Il server ha chiuso il collegamento.", "El servidor cerró la conexión.", "Le serveur a fermé la connexion.", "Der Server hat die Verbindung getrennt."}},
{S_V_ERR_MEMORY, {"Not enough memory: close other apps and retry.", "Memoria insufficiente: chiudi altre app e riprova.", "Memoria insuficiente: cierra otras apps.", "Mémoire insuffisante : fermez d'autres apps.", "Zu wenig Speicher: andere Apps schließen."}},
{S_V_CONNECTING, {"Connecting...", "Collegamento...", "Conectando...", "Connexion...", "Verbinde..."}},
{S_V_SEARCH_AGAIN, {"Search again", "Cerca di nuovo", "Buscar otra vez", "Rechercher", "Erneut suchen"}},
{S_NEXT, {"Not working? Try:", "Non funziona? Prova:", "¿No funciona? Prueba:", "Ça ne marche pas ? Essayez :", "Klappt nicht? Versuche:"}},
{S_NEXT_NOW, {"Recommended now:", "Consigliato adesso:", "Recomendado ahora:", "Conseillé maintenant :", "Jetzt empfohlen:"}},
{S_OTHER_DEVICE, {"Pick another device", "Scegli un altro dispositivo", "Elige otro dispositivo", "Choisir un autre appareil", "Anderes Gerät wählen"}},
{S_PAUSED, {"Paused", "In pausa", "En pausa", "En pause", "Pausiert"}},
{S_PAUSED_D, {"The link stays up. Tap Resume to go back to the screen.", "Il collegamento resta attivo. Tocca Riprendi per tornare allo schermo.", "La conexión sigue activa. Toca Reanudar para volver.", "La liaison reste active. Touchez Reprendre pour revenir.", "Die Verbindung bleibt. Fortsetzen tippen, um zurückzukehren."}},
{S_RESUME, {"Resume", "Riprendi", "Reanudar", "Reprendre", "Fortsetzen"}},
{S_DISCONNECT, {"Disconnect", "Disconnetti", "Desconectar", "Déconnecter", "Trennen"}},
{S_SWIPE_HINT, {"To leave the screen: swipe in from the left edge.", "Per uscire dallo schermo: scorri dal bordo sinistro.", "Para salir: desliza desde el borde izquierdo.", "Pour quitter : glissez depuis le bord gauche.", "Zum Verlassen: vom linken Rand wischen."}},
{S_ENDED, {"Connection ended", "Collegamento terminato", "Conexión terminada", "Connexion terminée", "Verbindung beendet"}},
{S_ASK_T, {"New device", "Nuovo dispositivo", "Nuevo dispositivo", "Nouvel appareil", "Neues Gerät"}},
{S_ASK_D, {"wants to use the board as a screen.", "vuole usare la scheda come schermo.", "quiere usar la placa como pantalla.", "veut utiliser la carte comme écran.", "möchte das Board als Bildschirm nutzen."}},
{S_ASK_ONCE, {"Allow", "Consenti", "Permitir", "Autoriser", "Erlauben"}},
{S_ASK_ALWAYS, {"Always allow", "Consenti sempre", "Permitir siempre", "Toujours autoriser", "Immer erlauben"}},
{S_ASK_DENY, {"Refuse", "Rifiuta", "Rechazar", "Refuser", "Ablehnen"}},
{S_OPT_AUTO, {"Open this app when a device connects", "Apri l'app quando un dispositivo si collega", "Abrir la app al conectar un dispositivo", "Ouvrir l'app quand un appareil se connecte", "App öffnen, wenn sich ein Gerät verbindet"}},
{S_OPT_ASK, {"Ask before a new device connects", "Chiedi conferma per i nuovi dispositivi", "Preguntar antes de un dispositivo nuevo", "Demander pour un nouvel appareil", "Bei neuen Geräten nachfragen"}},
{S_OPT_FORGET, {"Forget trusted devices", "Dimentica i dispositivi fidati", "Olvidar dispositivos de confianza", "Oublier les appareils de confiance", "Vertraute Geräte vergessen"}},
{S_OPT_FORGOT, {"Trusted devices forgotten", "Dispositivi fidati dimenticati", "Dispositivos olvidados", "Appareils oubliés", "Geräte vergessen"}},
{S_OPT_USB, {"High-speed USB-C port", "Porta USB-C ad alta velocità", "Puerto USB-C de alta velocidad", "Port USB-C haute vitesse", "Highspeed-USB-C-Port"}},
{S_OPT_USB_PC, {"PC mode (second screen)", "Modalità PC (secondo schermo)", "Modo PC (segunda pantalla)", "Mode PC (second écran)", "PC-Modus (Zweitbildschirm)"}},
{S_OPT_USB_ACC, {"Accessories (speakers, keyboard, mouse)", "Accessori (casse, tastiera, mouse)", "Accesorios (altavoces, teclado, ratón)", "Accessoires (enceintes, clavier, souris)", "Zubehör (Lautsprecher, Tastatur, Maus)"}},
{S_OPT_REBOOT_NOTE, {"Applies after a restart.", "Si applica al riavvio.", "Se aplica al reiniciar.", "S'applique au redémarrage.", "Gilt nach einem Neustart."}},
{S_DONE, {"Done", "Fatto", "Hecho", "OK", "Fertig"}},
{S_STEP_OF, {"Step %d of %d", "Passo %d di %d", "Paso %d de %d", "Étape %d sur %d", "Schritt %d von %d"}},
{S_LIVE_WITH, {"Connected: %s", "Collegato: %s", "Conectado: %s", "Connecté : %s", "Verbunden: %s"}},
{S_V_USER, {"Mac user", "Utente Mac", "Usuario del Mac", "Utilisateur Mac", "Mac-Benutzer"}},
{S_V_MAC_ALT, {"No VNC password? Type the Mac's user name and login password instead.",
                  "Niente password VNC? Scrivi invece nome utente e password di accesso del Mac.",
                  "¿Sin contraseña VNC? Escribe el usuario y la contraseña de inicio del Mac.",
                  "Pas de mot de passe VNC ? Tapez le nom d'utilisateur et le mot de passe du Mac.",
                  "Kein VNC-Passwort? Gib stattdessen Benutzername und Anmeldepasswort des Macs ein."}},
{S_SUG_USB_NODRV, {"A PC is connected by USB but sends no picture: install the Windows driver, or use Wi-Fi.",
                      "Un PC è collegato via USB ma non manda immagini: installa il driver Windows oppure usa il Wi-Fi.",
                      "Hay un PC conectado por USB pero no envía imagen: instala el driver de Windows o usa el Wi-Fi.",
                      "Un PC est branché en USB mais n'envoie pas d'image : installez le pilote Windows ou utilisez le Wi-Fi.",
                      "Ein PC ist per USB verbunden, sendet aber kein Bild: Windows-Treiber installieren oder WLAN nutzen."}},
{S_SUG_NO_NET, {"No network: the Wi-Fi methods need the board on the same network as the device.",
                   "Nessuna rete: i metodi senza cavo richiedono la scheda sulla stessa rete del dispositivo.",
                   "Sin red: los métodos sin cable necesitan la placa en la misma red que el dispositivo.",
                   "Pas de réseau : les méthodes sans fil exigent la carte sur le même réseau.",
                   "Kein Netzwerk: kabellose Methoden brauchen das Board im selben Netz."}},
{S_SUG_VNC_FAIL, {"The last VNC connection failed: %s", "L'ultimo collegamento VNC non è riuscito: %s", "La última conexión VNC falló: %s", "La dernière connexion VNC a échoué : %s", "Die letzte VNC-Verbindung schlug fehl: %s"}},
{S_SUG_CAST_WAIT, {"%s is connected: share a screen from the page to see it here.",
                      "%s è collegato: condividi uno schermo dalla pagina per vederlo qui.",
                      "%s está conectado: comparte una pantalla desde la página para verla aquí.",
                      "%s est connecté : partagez un écran depuis la page pour le voir ici.",
                      "%s ist verbunden: teile einen Bildschirm auf der Seite, um ihn hier zu sehen."}},
{S_SUG_DRIVER, {"Driver guide", "Guida driver", "Guía del driver", "Guide pilote", "Treiber-Anleitung"}},
{S_SUG_WIFI, {"Use Wi-Fi", "Usa il Wi-Fi", "Usar Wi-Fi", "Utiliser le Wi-Fi", "WLAN nutzen"}},
{S_SUG_RETRY, {"Retry", "Riprova", "Reintentar", "Réessayer", "Erneut"}},
{S_SUG_OPEN, {"Open", "Apri", "Abrir", "Ouvrir", "Öffnen"}},
{S_DONE_NEXT, {"Done, next", "Fatto, avanti", "Hecho, siguiente", "Fait, suivant", "Erledigt, weiter"}},
{S_QUICK, {"Quick start from any computer: open  http://%s:7070  in the browser.",
              "Avvio rapido da qualsiasi computer: apri  http://%s:7070  nel browser.",
              "Inicio rápido desde cualquier ordenador: abre  http://%s:7070  en el navegador.",
              "Démarrage rapide depuis un ordinateur : ouvrez  http://%s:7070  dans le navigateur.",
              "Schnellstart von jedem Computer: öffne  http://%s:7070  im Browser."}},
{S_OPT_FORGET_RECENT, {"Forget recent connections", "Dimentica i collegamenti recenti", "Olvidar conexiones recientes", "Oublier les connexions récentes", "Letzte Verbindungen vergessen"}},
};
// clang-format on
constexpr bool ss_rows_in_order(void) {
    for (int i = 0; i < (int)(sizeof(kSsRows) / sizeof(kSsRows[0])); i++)
        if (kSsRows[i].id != i) return false;
    return sizeof(kSsRows) / sizeof(kSsRows[0]) == S_COUNT;
}
static_assert(ss_rows_in_order(), "kSsRows: one row per SsStr, in enum order");

static inline const char *ss_tr(SsStr id) {
    int l = (int)nv_i18n_get_lang();
    if (l < 0 || l >= NV_LANG_COUNT) l = NV_LANG_EN;
    const char *s = kSsRows[id].t[l];
    return (s && s[0]) ? s : kSsRows[id].t[NV_LANG_EN];
}
