// angler.h - generated by art/gen9.py (angler_post): the rod tip in each pose's billboard,
// as fractions of its width (0 = left) and height (0 = bottom). Poses: idle, wind, cast, reel.
static const float k_rod_tip[4][2] = { { 0.879f, 0.996f }, { 0.941f, 0.996f }, { 0.973f, 0.996f }, { 0.898f, 0.996f } };
static const float k_body_u[4] = { 0.311f, 0.262f, 0.209f, 0.248f };   // the figure's centre line (fraction of width)
