// digits.h - generated by art/digits.py: slanted digit cells in img/dg.565 ("0123456789.:-").
#define DG_H 34
static const short k_dg_x[13] = { 0, 34, 68, 102, 136, 170, 204, 238, 272, 306, 340, 353, 366 };
static const unsigned char k_dg_w[13] = { 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 12, 12, 33 };
