#!/usr/bin/env python3
# gen_ss_icons.py — MDI glyphs for the Second Screen wizard as LVGL 9 A8 (alpha-only) images.
# A8 images are drawn in the style's image_recolor color, so one glyph serves every theme/state.
# Output: components/nv_secondscreen/ss_icons.c + ss_icons.h  (needs PyMuPDF: pip install pymupdf)
#
#   python tools/gen_ss_icons.py
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MDI = os.path.join(r'D:\NucleoV2', 'system', 'icons', 'mdi', 'svg')
OUT_C = os.path.join(ROOT, 'components', 'nv_secondscreen', 'ss_icons.c')
OUT_H = os.path.join(ROOT, 'components', 'nv_secondscreen', 'include', 'ss_icons.h')

# (mdi name, C name, size)
ICONS = [
    ('microsoft-windows', 'win', 64), ('apple', 'apple', 64), ('linux', 'linux', 64),
    ('android', 'android', 64), ('web', 'web', 64), ('monitor-share', 'screen', 96),
    ('usb', 'usb', 40), ('wifi', 'wifi', 40), ('remote-desktop', 'vnc', 40), ('cast-connected', 'cast', 40),
    ('lan', 'lan', 40), ('google-chrome', 'browser', 40),
    ('check-circle', 'ok', 26), ('alert-circle', 'warn', 26), ('close-circle', 'fail', 26),
    ('circle-outline', 'todo', 26), ('chevron-right', 'chev', 26), ('arrow-left', 'back', 26),
    ('refresh', 'refresh', 26), ('cog', 'cog', 26), ('download', 'download', 26),
    ('shield-check', 'shield', 26), ('gesture-swipe-right', 'swipe', 40), ('help-circle', 'help', 26),
    ('lock', 'lock', 26), ('play-circle', 'play', 40), ('link-variant-off', 'unlink', 26),
    ('play-circle', 'cur', 26),
]


def render_a8(name, size):
    import fitz
    doc = fitz.open(os.path.join(MDI, name + '.svg'))
    page = doc[0]
    zoom = size / max(page.rect.width, page.rect.height)
    pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=True)
    w, h, n = pix.width, pix.height, pix.n
    a = bytearray(size * size)
    ox, oy = (size - w) // 2, (size - h) // 2
    s = pix.samples
    for y in range(h):
        for x in range(w):
            p = (y * w + x) * n
            # MDI glyphs are black on transparent: coverage = alpha channel
            a[(y + oy) * size + (x + ox)] = s[p + n - 1]
    return bytes(a)


def main():
    c = ['// Generated by tools/gen_ss_icons.py — do not edit. MDI icons (Apache-2.0, Pictogrammers).',
         '#include "ss_icons.h"', '']
    h = ['// Generated by tools/gen_ss_icons.py — Second Screen wizard icons (A8: tint with image_recolor).',
         '#pragma once', '#include "lvgl.h"', '', '#ifdef __cplusplus', 'extern "C" {', '#endif', '']
    for mdi, cname, size in ICONS:
        data = render_a8(mdi, size)
        c.append(f'static const uint8_t ss_ic_{cname}_px[] = {{')
        for i in range(0, len(data), 24):
            c.append('    ' + ','.join(str(b) for b in data[i:i + 24]) + ',')
        c.append('};')
        c.append(f'const lv_image_dsc_t ss_ic_{cname} = {{')
        c.append(f'    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, '
                 f'.w = {size}, .h = {size}, .stride = {size} }},')
        c.append(f'    .data_size = sizeof(ss_ic_{cname}_px),')
        c.append(f'    .data = ss_ic_{cname}_px,')
        c.append('};')
        c.append('')
        h.append(f'extern const lv_image_dsc_t ss_ic_{cname};   // {mdi} {size}px')
    h += ['', '#ifdef __cplusplus', '}', '#endif', '']
    with open(OUT_C, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(c))
    with open(OUT_H, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(h))
    print('icons:', len(ICONS), '->', OUT_C)


if __name__ == '__main__':
    main()
