#!/usr/bin/env python3
"""Write docs/SHELL.md from the command table in components/nv_apps/term_sh.cpp, so the reference
people and AI agents read always matches the firmware:

    python tools/gen_shell_doc.py          # rewrite docs/SHELL.md
    python tools/gen_shell_doc.py --check  # exit 1 if docs/SHELL.md is out of date (CI)"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "components", "nv_apps", "term_sh.cpp")
OUT = os.path.join(ROOT, "docs", "SHELL.md")

ROW = re.compile(r'^\s*\{"([^"]+)",\s*b_\w+,\s*"((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)"\},', re.M)
ALIAS = re.compile(r'\{"([^"]+)",\s*"([^"]+)"\}')

HEAD = """# NucleoOS shell reference

<!-- Generated by tools/gen_shell_doc.py from components/nv_apps/term_sh.cpp. Do not edit. -->

The Terminal app runs a small POSIX-flavoured shell with GNU-style core utilities. Open it on the
device, or from the web desktop. `help` lists the commands, and `help CMD` or `CMD --help` prints
the usage line for one of them.

## Differences from bash (read this first)

Supported: `'single'` and `"double"` quotes, `\\` escapes, `$VAR`, `${VAR}`, `$?`, `~`, globs
(`* ? [..]`), pipes `|`, redirections `> >> < 2> 2>&1` and `/dev/null`, lists `; && ||`, `#` comments,
`NAME=value`, `export`, `unset`.

Not supported: command substitution (`$(...)` and backticks), `if`/`for`/`while`/`case`, functions,
script files (`sh file`, `source`), background jobs (`&`), here-documents, arithmetic `$((...))`,
symbolic links, users and permissions. Use `xargs` instead of loops, for example
`find /sdcard -name '*.txt' | xargs -I F wc -l F`.

- Paths: `/` is a virtual directory listing the volumes (`/sdcard`, `/usb0`..`/usb6`). The home
  directory is `~`.
- Pipes run one stage after another through memory, with a 1 MB cap on each stage's output.
- Option support is a subset: the usage lines below list every flag each command accepts.
- A name that is not a built-in runs the installed terminal program of that name (`lua`, `sqlite3`,
  `js`, ...). `apps` lists them. Graphical apps open from Home, not from the shell.

## Commands

| Command | Usage | Description |
|---|---|---|
"""


def md(s):
    return s.replace("\\\"", "\"").replace("\\\\", "\\").replace("|", "\\|")


def render():
    with open(SRC, encoding="utf-8") as f:
        src = f.read()
    start = src.index("kBuiltins[]")
    table = src[start:src.index("};", start)]
    rows = ROW.findall(table)
    if len(rows) < 50:
        raise SystemExit(f"parsed only {len(rows)} commands from {SRC}")
    out = [HEAD]
    for name, usage, desc in rows:
        out.append(f"| `{md(name)}` | `{md(usage)}` | {md(desc)} |\n")
    a0 = src.index("kAliases[]")
    aliases = ALIAS.findall(src[a0:src.index("};", a0)])
    out.append("\n## Aliases\n\n")
    out.append(", ".join(f"`{a}` = `{n}`" for a, n in aliases) + "\n")
    return "".join(out)


def main():
    text = render()
    if "--check" in sys.argv:
        try:
            with open(OUT, encoding="utf-8") as f:
                same = f.read() == text
        except OSError:
            same = False
        if not same:
            print("::error file=docs/SHELL.md::out of date: run python tools/gen_shell_doc.py")
            return 1
        print("docs/SHELL.md up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
