"""NucleoOS logo -> LVGL ARGB8888 images for the classic desktop (Start button).

Source: tools/assets/nucleo_logo_192.png (the NucleoOS crystal nucleus, same as the Cardputer
edition's web shell icon). The sphere is cut out of its dark square with a soft circular mask so it
sits on any taskbar colour. Output: components/nv_ui/generated/nv_logo.c (+ nv_logo.h).

    python tools/gen_logo.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "assets" / "nucleo_logo_192.png"
OUT = ROOT / "components" / "nv_ui" / "generated"
SIZES = (22,)   # the Start button


def sphere(size: int) -> Image.Image:
    src = Image.open(SRC).convert("RGBA")
    w, h = src.size
    # The sphere fills ~80 % of the icon, centred.
    r = int(w * 0.40)
    cx, cy = w // 2, h // 2
    crop = src.crop((cx - r, cy - r, cx + r, cy + r))
    big = 4 * size
    crop = crop.resize((big, big), Image.LANCZOS)
    mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(mask).ellipse((1, 1, big - 2, big - 2), fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(2))
    crop.putalpha(mask)
    return crop.resize((size, size), Image.LANCZOS)


def c_array(name: str, img: Image.Image) -> str:
    px = img.load()
    w, h = img.size
    data = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            data += [b, g, r, a]                      # LVGL ARGB8888 = B, G, R, A in memory
    rows = [", ".join("0x%02x" % v for v in data[i:i + 16]) for i in range(0, len(data), 16)]
    body = ",\n    ".join(rows)
    return (
        f"static const uint8_t {name}_map[] = {{\n    {body}\n}};\n"
        f"const lv_image_dsc_t {name} = {{\n"
        f"    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888,"
        f" .w = {w}, .h = {h}, .stride = {w * 4} }},\n"
        f"    .data_size = sizeof({name}_map),\n"
        f"    .data = {name}_map,\n}};\n"
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    parts = ["// Generated by tools/gen_logo.py from tools/assets/nucleo_logo_192.png - do not edit.\n",
             '#include "nv_logo.h"\n\n']
    for s in SIZES:
        parts.append(c_array(f"nv_logo_{s}", sphere(s)) + "\n")
    (OUT / "nv_logo.c").write_text("".join(parts), encoding="utf-8")
    (OUT / "nv_logo.h").write_text(
        "// Generated by tools/gen_logo.py - the NucleoOS logo (crystal nucleus), ARGB8888.\n"
        "#pragma once\n#include \"lvgl.h\"\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n"
        + "".join(f"extern const lv_image_dsc_t nv_logo_{s};\n" for s in SIZES)
        + "#ifdef __cplusplus\n}\n#endif\n",
        encoding="utf-8")
    sphere(160).save(ROOT / "tools" / "assets" / "nucleo_logo_preview.png")
    print("ok:", ", ".join(f"{s}px" for s in SIZES))


if __name__ == "__main__":
    main()
