"""Recovery app assets -> recovery/main/rec_assets.c (+ rec_assets.h).

The recovery app (recovery/) has no LVGL: it draws straight into the panel framebuffer. This bakes
what it needs into plain C arrays:
  * three anti-aliased font sizes (8-bit alpha glyphs, Latin-1 32..255) from Montserrat Medium
    (SIL Open Font License, the face LVGL's built-in fonts use; read from the LVGL component);
  * the NucleoOS logo (tools/assets/nucleo_logo_192.png, the same source as tools/gen_logo.py) as
    ARGB8888.

    python tools/gen_recovery_assets.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "managed_components" / "lvgl__lvgl" / "scripts" / "built_in_font" / "Montserrat-Medium.ttf"
LOGO = ROOT / "tools" / "assets" / "nucleo_logo_192.png"
OUT = ROOT / "recovery" / "main"
SIZES = {"title": 40, "body": 26, "small": 20}
LOGO_PX = 112
FIRST, LAST = 32, 255


def glyphs(size: int):
    font = ImageFont.truetype(str(FONT), size)
    ascent, descent = font.getmetrics()
    out = []
    bitmap = bytearray()
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        if 0x7F <= cp < 0xA0:          # C1 controls: empty
            out.append((0, 0, 0, 0, 0, 0))
            continue
        adv = int(round(font.getlength(ch)))
        box = font.getbbox(ch)        # relative to the text origin (top of ascent)
        if box is None or box[2] <= box[0] or box[3] <= box[1]:
            out.append((len(bitmap), 0, 0, 0, 0, adv))
            continue
        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
        out.append((len(bitmap), w, h, x0, y0, adv))
        bitmap += img.tobytes()
    return out, bytes(bitmap), ascent + descent, ascent


def logo() -> Image.Image:
    src = Image.open(LOGO).convert("RGBA")
    w, h = src.size
    r = int(w * 0.40)
    crop = src.crop((w // 2 - r, h // 2 - r, w // 2 + r, h // 2 + r))
    big = 4 * LOGO_PX
    crop = crop.resize((big, big), Image.LANCZOS)
    mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(mask).ellipse((1, 1, big - 2, big - 2), fill=255)
    crop.putalpha(mask.filter(ImageFilter.GaussianBlur(2)))
    return crop.resize((LOGO_PX, LOGO_PX), Image.LANCZOS)


def arr(name: str, data: bytes, ctype: str = "uint8_t") -> str:
    rows = [", ".join(str(b) for b in data[i:i + 24]) for i in range(0, len(data), 24)]
    return f"static const {ctype} {name}[{len(data)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    c = ["// Generated by tools/gen_recovery_assets.py - do not edit.\n",
         "// Font: Montserrat Medium (SIL Open Font License 1.1). Logo: tools/assets/nucleo_logo_192.png.\n",
         '#include "rec_assets.h"\n\n']
    for key, size in SIZES.items():
        table, bitmap, line_h, ascent = glyphs(size)
        c.append(arr(f"s_{key}_bits", bitmap))
        rows = ",\n    ".join("{%d, %d, %d, %d, %d, %d}" % g for g in table)
        c.append(f"static const rec_glyph_t s_{key}_glyphs[{len(table)}] = {{\n    {rows}\n}};\n")
        c.append(f"const rec_font_t rec_font_{key} = {{ s_{key}_glyphs, s_{key}_bits, {line_h}, {ascent}, "
                 f"{FIRST}, {LAST} }};\n\n")
    img = logo()
    px = img.tobytes()   # R, G, B, A
    c.append(arr("s_logo_rgba", px))
    c.append(f"const rec_image_t rec_logo = {{ s_logo_rgba, {LOGO_PX}, {LOGO_PX} }};\n")
    (OUT / "rec_assets.c").write_text("".join(c), encoding="utf-8")

    h = """// Generated by tools/gen_recovery_assets.py - do not edit.
#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t offset;   // into the font's alpha bitmap
    uint8_t  w, h;
    int8_t   x, y;     // top-left relative to the pen (x) and the line top (y)
    uint8_t  adv;
} rec_glyph_t;

typedef struct {
    const rec_glyph_t *glyphs;
    const uint8_t     *bits;    // 8-bit alpha, row-major per glyph
    uint8_t            line_h;
    uint8_t            ascent;
    uint8_t            first, last;
} rec_font_t;

typedef struct {
    const uint8_t *rgba;        // R, G, B, A per pixel
    uint16_t       w, h;
} rec_image_t;

extern const rec_font_t rec_font_title;
extern const rec_font_t rec_font_body;
extern const rec_font_t rec_font_small;
extern const rec_image_t rec_logo;

#ifdef __cplusplus
}
#endif
"""
    (OUT / "rec_assets.h").write_text(h, encoding="utf-8")
    print("wrote", OUT / "rec_assets.c")


if __name__ == "__main__":
    main()
