#!/usr/bin/env python3
# gen_icons.py — rasterize selected flat-color SVGs to LVGL 9 ARGB8888 C-arrays.
# Output: components/nv_ui/generated/nv_icons.c + components/nv_ui/include/nv_icons.h
import os, fitz

ROOT = r'D:\NucleoV2'
SVG_DIR = os.path.join(ROOT, 'system', 'icons', 'flat-color', 'svg')
MDI_DIR = os.path.join(ROOT, 'system', 'icons', 'mdi', 'svg')
OUT_C = os.path.join(ROOT, 'components', 'nv_ui', 'generated', 'nv_icons.c')
OUT_H = os.path.join(ROOT, 'components', 'nv_ui', 'include', 'nv_icons.h')
SIZE = 80

# (svg basename, C identifier[, opts]). opts: {'dir': 'mdi', 'tint': (r,g,b)} to render a
# monochrome MDI glyph tinted to a fixed color (keeps antialiased alpha).
REC_RED = (232, 65, 78)
ICONS = [
    ('settings', 'settings'),
    ('opened_folder', 'files'),
    ('assistant', 'anima'),
    ('combo_chart', 'diag'),
    ('command_line', 'terminal'),
    ('gallery', 'gallery'),
    ('music', 'music'),
    ('camera', 'camera'),
    ('calculator', 'calc'),
    ('todo_list', 'tasks'),
    ('document', 'notes'),   # Notes app (was reusing the todo/tasks icon)
    ('shop', 'apps'),        # Apps store (WASM app manager) — colorful storefront
    ('puzzle', 'wasm'),      # installed WASM app tiles
    ('multiple_devices', 'screen'),   # Second Screen (USB extended display) — laptop + 2nd device
    ('film', 'video'),       # Video player (MJPEG/H.264)
    ('microphone', 'recorder', {'dir': 'mdi', 'tint': REC_RED}),   # Voice Recorder (MDI, tinted)
    ('area_chart', 'sysmon'),   # System Monitor (task manager) — perf-graph look
    # ---- WASM app icons (mdi, tinted) — mapped to installed apps by id in apps_app.cpp ----
    ('timer',                'wtimer',  {'dir': 'mdi', 'tint': (84, 162, 255)}),   # Timer
    ('flashlight',           'wtorch',  {'dir': 'mdi', 'tint': (255, 200, 60)}),   # Torch
    ('piano',                'wpiano',  {'dir': 'mdi', 'tint': (150, 120, 255)}),  # Pianino
    ('target',               'wcannon', {'dir': 'mdi', 'tint': (240, 120, 60)}),   # Cannon
    ('tank',                 'wtank',   {'dir': 'mdi', 'tint': (120, 150, 110)}),  # Tanks
    ('alphabetical-variant', 'wabc',    {'dir': 'mdi', 'tint': (255, 193, 7)}),    # ABC 123
    ('code-braces',          'wcode',   {'dir': 'mdi', 'tint': (46, 196, 198)}),   # Ciao SDK
    ('gamepad-variant',      'wgame',   {'dir': 'mdi', 'tint': (232, 84, 140)}),   # generic game fallback
    ('bug',                  'wbug',    {'dir': 'mdi', 'tint': (150, 156, 172)}),  # Wedge (test)
]


def render_bgra(svg_path, size, tint=None):
    """Render an SVG centered on a size×size transparent canvas, return BGRA bytes.
    If `tint` (r,g,b) is given, force every opaque pixel to that color (for mono MDI glyphs),
    keeping the antialiased alpha so edges stay smooth."""
    doc = fitz.open(svg_path)
    page = doc[0]
    zoom = size / max(page.rect.width, page.rect.height)
    pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=True)
    src = pix.samples  # RGBA, pix.width×pix.height
    sw, sh, n = pix.width, pix.height, pix.n
    ox, oy = (size - sw) // 2, (size - sh) // 2
    out = bytearray(size * size * 4)  # zero => transparent
    for y in range(sh):
        for x in range(sw):
            si = (y * sw + x) * n
            r, g, b, a = src[si], src[si + 1], src[si + 2], (src[si + 3] if n == 4 else 255)
            if tint and a > 0:
                r, g, b = tint
            di = ((oy + y) * size + (ox + x)) * 4
            out[di + 0] = b  # LVGL ARGB8888 memory order = B,G,R,A
            out[di + 1] = g
            out[di + 2] = r
            out[di + 3] = a
    return bytes(out)


def emit():
    os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    with open(OUT_C, 'w') as c, open(OUT_H, 'w') as h:
        h.write('// AUTO-GENERATED by tools/gen_icons.py — do not edit.\n')
        h.write('// Color launcher/app icons (icons8 flat-color, MIT) as LVGL 9 ARGB8888.\n')
        h.write('#pragma once\n#include "lvgl.h"\n\n#ifdef __cplusplus\nextern "C" {\n#endif\n\n')

        c.write('// AUTO-GENERATED by tools/gen_icons.py — do not edit.\n')
        c.write('#include "nv_icons.h"\n\n')

        for entry in ICONS:
            svg, name = entry[0], entry[1]
            opts = entry[2] if len(entry) > 2 else {}
            base = MDI_DIR if opts.get('dir') == 'mdi' else SVG_DIR
            path = os.path.join(base, svg + '.svg')
            data = render_bgra(path, SIZE, opts.get('tint'))
            c.write(f'static const uint8_t nv_icon_{name}_map[] = {{\n')
            for i in range(0, len(data), 16):
                c.write('  ' + ','.join(str(b) for b in data[i:i + 16]) + ',\n')
            c.write('};\n')
            c.write(f'const lv_image_dsc_t nv_icon_{name} = {{\n')
            c.write('  .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888,\n')
            c.write(f'             .flags = 0, .w = {SIZE}, .h = {SIZE}, .stride = {SIZE * 4}, .reserved_2 = 0 }},\n')
            c.write(f'  .data_size = {len(data)},\n')
            c.write(f'  .data = nv_icon_{name}_map,\n}};\n\n')
            h.write(f'extern const lv_image_dsc_t nv_icon_{name};\n')
            print(f'  {svg}.svg -> nv_icon_{name} ({len(data)} bytes)')

        h.write('\n#ifdef __cplusplus\n}\n#endif\n')
    print(f'wrote {OUT_C}\nwrote {OUT_H}')


if __name__ == '__main__':
    emit()
