"""Import Home Assistant's own intent test sentences as ANIMA L0 paraphrases.

  git clone --depth 1 https://github.com/home-assistant/intents.git /tmp/ha-intents
  python tools/import_ha_intents.py /tmp/ha-intents          # writes tools/anima_phrases_ha.txt
  python tools/gen_anima_phrases.py                           # then regenerate the table + tests

Source: home-assistant/intents (https://github.com/home-assistant/intents), CC-BY-4.0. Only the
tests/<lang>/<Intent>/default.yaml sentences of intents ANIMA can run are taken, and only literal ones:
no area, no device name, no number (ANIMA has no slot for them yet). Each maps to the canonical phrase
ANIMA already understands. Needs PyYAML (a dev tool: the generated .txt is what gets committed).
"""
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tools", "anima_phrases_ha.txt")

# Home Assistant intent -> ANIMA canonical per language; a callable decides per sentence.
UP_IT = re.compile(r"\b(su|alz|aument|increment|più forte|piu forte)")
DOWN_IT = re.compile(r"\b(giù|giu|abbass|diminuisc|decrement|più piano|piu piano)")
UP_EN = re.compile(r"\b(up|raise|increase|louder|turn up)\b")
DOWN_EN = re.compile(r"\b(down|lower|decrease|quieter|turn down)\b")


def relative(s, lang):
    up, down = (UP_IT, DOWN_IT) if lang == "it" else (UP_EN, DOWN_EN)
    u, d = bool(up.search(s)), bool(down.search(s))
    if u == d:
        return None                     # no direction, or both: not a sentence we can map with certainty
    if lang == "it":
        return "alza il volume" if u else "abbassa il volume"
    return "turn the volume up" if u else "turn the volume down"


MAP = {
    "HassGetCurrentTime":    {"it": "che ore sono",       "en": "what time is it"},
    "HassGetCurrentDate":    {"it": "che giorno è oggi",  "en": "what day is it today"},
    "HassMediaPause":        {"it": "pausa",              "en": "pause the song"},
    "HassMediaUnpause":      {"it": "riprendi la musica", "en": "resume"},
    "HassMediaPlayerMute":   {"it": "volume al minimo",   "en": "set the volume to 0"},
    "HassMediaPlayerUnmute": {"it": "alza il volume",     "en": "turn the volume up"},
    "HassNevermind":         {"it": "no",                 "en": "no"},
    "HassSetVolumeRelative": relative,
}


def literal(s):
    # Our template syntax uses ( ) [ ] |: a sentence carrying them is not literal; skip it.
    return not re.search(r"[()\[\]|{}<>;0-9]", s)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    ha = sys.argv[1]
    groups = {}   # (lang, canonical) -> [sentences]
    seen = 0
    for lang in ("it", "en"):
        for intent, target in MAP.items():
            path = os.path.join(ha, "tests", lang, intent, "default.yaml")
            if not os.path.exists(path):
                continue
            doc = yaml.safe_load(open(path, encoding="utf-8"))
            for block in doc.get("tests", []):
                if block.get("slots") and intent != "HassSetVolumeRelative":
                    continue
                for s in block.get("sentences", []):
                    s = " ".join(str(s).strip().lower().split())
                    seen += 1
                    if not literal(s):
                        continue
                    canon = target(s, lang) if callable(target) else target[lang]
                    if canon:
                        groups.setdefault((lang, canon), [])
                        if s not in groups[(lang, canon)]:
                            groups[(lang, canon)].append(s)
    rev = os.popen('git -C "%s" log -1 --format=%%h' % ha).read().strip() or "unknown"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# GENERATED by tools/import_ha_intents.py from home-assistant/intents @ %s - do not edit.\n" % rev)
        f.write("# Source: https://github.com/home-assistant/intents (tests/<lang>/<Intent>/default.yaml),\n")
        f.write("# licensed CC-BY-4.0 (c) Home Assistant contributors. Read by tools/gen_anima_phrases.py.\n\n")
        for (lang, canon), ss in sorted(groups.items()):
            f.write("= %s %s\n" % (lang, canon))
            for s in ss:
                f.write(s + "\n")
            f.write("\n")
    n = sum(len(v) for v in groups.values())
    print("%d sentences read, %d imported into %d groups -> %s" % (seen, n, len(groups), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
